Improve ESS config linkage into XDG_CONFIG_HOME

diff --git a/bin/dotfile b/bin/dotfile
--- a/bin/dotfile
+++ b/bin/dotfile
@@ -4,12 +4,6 @@ set -Eeu -o pipefail
 # shellcheck source=/dev/null
 source "$(koopa header bash)"
 
-# Symlink dot file.
-# Updated 2019-06-26.
-
-# Note that relative file path in dotfiles repo can be used as input.
-# The destination file should be specified without a leading period.
-
 
 
 # Usage                                                                     {{{1
@@ -17,7 +11,14 @@ source "$(koopa header bash)"
 
 usage() {
 cat << EOF
-usage: dotfile [-h] RELATIVE_PATH [SYMLINK_NAME]
+usage: dotfile [-h|--help] [--config] [--force] [--private] [--quiet]
+    RELATIVE_PATH [SYMLINK_NAME]
+
+Symlink a dot file.
+Updated 2019-09-20.
+
+Note that relative file path in dotfiles repo can be used as input.
+The destination file should be specified without a leading period.
 
 required positional arguments:
     1: relative_path
@@ -30,18 +31,20 @@ optional positional arguments:
 optional arguments:
     -h, --help
         Show this help message and exit.
-    -f, --force 
+    --config
+        Symlink into XDG config directory instead of user home.
+        This path is defined by 'XDG_CONFIG_HOME' and defaults to '~/.config/'.
+    --force
         Force overwrite.
         Applies to symlinks only.
-    -p, --private
-        Private dot file.
-        Currently only works for Mike's configuration.
-    -q, --quiet
-        Quiet mode. Don't print messages.
+    --private
+        Link a private dot file.
+        Checks in 'scripts-private/' directory in koopa config.
+        Defaults to '~/.config/koopa/scripts-private/'.
 EOF
 }
 
-[[ -z "$*" ]] && usage && exit
+[[ -z "$*" ]] && usage && exit 0
 
 
 
@@ -53,23 +56,27 @@ EOF
 
 PARAMS=""
 
+config=0
+force=0
+private=0
+
 while (("$#"))
 do
     case "$1" in
-        -f|--force)
+        --config)
+            config=1
+            shift 1
+            ;;
+        --force)
             force=1
             shift 1
             ;;
-        -h|--help)
+        --help)
             usage
             exit 0
             ;;
-        -p|--private)
+        --private)
             private=1
-            shift 1
-            ;;
-        -q|--quiet)
-            quiet=1
             shift 1
             ;;
         --)
@@ -103,7 +110,7 @@ unset -f usage
 # Note that we're creating a symlink in local user config.
 dot_dir="$(_koopa_config_dir)/dotfiles"
 
-# Create a dotfile symlink, if necessary.
+# Create a dotfile symlink in config dir, if necessary.
 dot_repo="$(_koopa_home)/dotfiles"
 if [[ -d "$dot_repo"  ]] && [[ ! -d "$dot_dir" ]]
 then
@@ -111,8 +118,8 @@ then
     ln -fnsv "$dot_repo" "$dot_dir"
 fi
 
-# Private file (experimental).
-if [[ "${private:-0}" -eq 1 ]]
+# Private file.
+if [[ "$private" -eq 1 ]]
 then
     dot_dir="${dot_dir}-private"
 fi
@@ -120,7 +127,7 @@ fi
 # Error if the dotfiles directory can't be found.
 if [[ ! -d "$dot_dir" ]]
 then
-    >&2 printf "Error: dotfiles directory missing: '%s'.\n" "$dot_dir"
+    >&2 printf "Error: Directory missing: '%s'.\n" "$dot_dir"
     exit 1
 fi
 
@@ -128,7 +135,7 @@ fi
 source_path="${dot_dir}/${1}"
 if [[ ! -f "$source_path" && ! -d "$source_path" ]]
 then
-    >&2 printf "Error: source missing: '%s'.\n" "$source_path"
+    >&2 printf "Error: Source file missing: '%s'.\n" "$source_path"
     exit 1
 fi
 
@@ -138,7 +145,14 @@ if [[ -z "$symlink_name" ]]
 then
     symlink_name="$(basename "$source_path")"
 fi
-symlink_path="${HOME}/.${symlink_name}"
+
+# Add link either in HOME (default) or XDG_CONFIG_HOME.
+if [[ "$config" -eq 1 ]]
+then
+    symlink_path="${XDG_CONFIG_HOME}/${symlink_name}"
+else
+    symlink_path="${HOME}/.${symlink_name}"
+fi
 
 # Inform the user when nuking a broken symlink.
 if [[ -L "$symlink_path" ]] && [[ ! -e "$symlink_path" ]]
@@ -150,9 +164,8 @@ fi
 # We're allowing force overwrite of existing symlinks only.
 if [[ -L "$symlink_path" ]] &&
     [[ -f "$symlink_path" || -d "$symlink_path" ]] &&
-    [[ -z "${force:-}" ]]
+    [[ "$force" -eq 0 ]]
 then
-    [[ -n "${quiet:-}" ]] && exit 0
     >&2 printf "Error: Existing symlink: '%s'.\n" "$symlink_path"
     exit 1
 elif [[ ! -L "$symlink_path" ]] && [[ -e "$symlink_path" ]]
@@ -161,10 +174,6 @@ then
     exit 1
 fi
 
-if [[ -z "${quiet:-}" ]]
-then
-    printf "Symlinking '%s'.\n" "$(basename "$symlink_path")"
-fi
-
+printf "Symlinking '%s'.\n" "$(basename "$symlink_path")"
 rm -fv "$symlink_path"
 ln -fnsv "$source_path" "$symlink_path"
