Update scripts

diff --git a/bin/extract-fastq b/bin/extract-fastq
--- a/bin/extract-fastq
+++ b/bin/extract-fastq
@@ -2,10 +2,12 @@
 set -Eeu -o pipefail
 
 # Extract FASTQs files inside a TAR file.
+# Modified 2019-06-18.
 
 file="$1"
-if [[ ! -f "$file" ]]; then
-    echo "${file} tar file does not exist."
+if [[ ! -f "$file" ]]
+then
+    >&2 printf "Error: %s tar file does not exist.\n" "$file"
     exit 1
 fi
 tar -xvf "$file" --wildcards "*.fastq.*"
diff --git a/bin/find-and-replace b/bin/find-and-replace
--- a/bin/find-and-replace
+++ b/bin/find-and-replace
@@ -2,21 +2,20 @@
 set -Eeu -o pipefail
 
 # Global find and replace in files using sed.
+# Modified 2019-06-18.
 
-pattern="$1"
-replacement="$2"
+from="$1"
+to="$2"
 
 # Check for unescaped slashes.
-if echo "$pattern" | grep -q "/" &&
-    echo "$pattern" | grep -Fqv "\\"
+if echo "$from" | grep -q "/" && echo "$from" | grep -Fqv "\\"
 then
-    >&2 echo "Error: Unescaped '/' detected in pattern."
+    >&2 printf "Error: Unescaped '/' detected: %s\n" "$from"
+    exit 1
+elif echo "$to" | grep -q "/" && echo "$to" | grep -Fqv "\\"
+then
+    >&2 printf "Error: Unescaped '/' detected: %s\n" "$to"
+    exit 1
 fi
 
-if echo "$replacement" | grep -q "/" &&
-    echo "$replacement" | grep -Fqv "\\"
-then
-    >&2 echo "Error: Unescaped '/' detected in replacement."
-fi
-
-find . -maxdepth 1 -type f -exec sed -i "s/${pattern}/${replacement}/g" {} \;
+find . -maxdepth 1 -type f -exec sed -i "s/${from}/${to}/g" {} \;
diff --git a/bin/install-anaconda3 b/bin/install-anaconda3
--- a/bin/install-anaconda3
+++ b/bin/install-anaconda3
@@ -9,32 +9,35 @@ set -Eeu -o pipefail
 source "${KOOPA_DIR}/include/shell/bash/functions.sh"
 
 prefix="${prefix:-${KOOPA_PREFIX}/anaconda3}"
-build_dir="${KOOPA_TMP_DIR}/build/anaconda3"
-
-version="$(koopa_version anaconda3)"
+tmp_dir="${KOOPA_TMP_DIR}/anaconda3"
+version="$(koopa variable anaconda3)"
 
 case "$OSTYPE" in
-    linux-gnu) script="Anaconda3-${version}-Linux-x86_64.sh";;
-      darwin*) script="Anaconda3-${version}-MacOSX-x86_64.sh";;
-            *) echo "${OSTYPE} is not supported."; exit 1;;
+    linux-gnu)
+        script="Anaconda3-${version}-Linux-x86_64.sh"
+        ;;
+    darwin*)
+        script="Anaconda3-${version}-MacOSX-x86_64.sh"
+        ;;
+    *)
+        >&2 printf "Error: %s is not supported." "$OSTYPE"
+        exit 1
+        ;;
 esac
 
 prefix_mkdir "$prefix"
 
 (
-    rm -rf "$build_dir"
-    mkdir -p "$build_dir"
-    cd "$build_dir"
-    echo "Downloading Anaconda installer."
+    rm -rf "$tmp_dir"
+    mkdir -p "$tmp_dir"
+    cd "$tmp_dir"
     curl -O "https://repo.anaconda.com/archive/${script}"
-    # Note that this script should not be run as root.
     bash "$script" -bf -p "$prefix"
-    rm -rf "$build_dir"
+    rm -rf "$tmp_dir"
 )
 
 prefix_chgrp "$prefix"
 
-echo "conda installed successfully."
 conda_exe="${prefix}/bin/conda"
-echo "$conda_exe"
-sh -c "$conda_exe --version"
+command -v "$conda_exe"
+"$conda_exe --version"
diff --git a/bin/install-perlbrew-system b/bin/install-perlbrew-system
--- a/bin/install-perlbrew-system
+++ b/bin/install-perlbrew-system
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 set -Eeu -o pipefail
 
-# Install Perlbrew system Perl
-# https://stackoverflow.com/questions/25188575
+# Install Perlbrew system Perl.
+# Modified 2019-06-18.
+
+# See also:
+# - https://stackoverflow.com/questions/25188575
 
 if [[ -x "/usr/local/bin/perl" ]]
 then
@@ -11,7 +14,7 @@ elif [[ -x "/usr/bin/perl" ]]
 then
     bin_dir="/usr/bin"
 else
-    >&2 echo "Error: Failed to detect system Perl."
+    >&2 printf "Error: Failed to detect system Perl.\n"
     exit 1
 fi
 
diff --git a/bin/os/fedora/sudo/sudo-install-git b/bin/os/fedora/sudo/sudo-install-git
--- a/bin/os/fedora/sudo/sudo-install-git
+++ b/bin/os/fedora/sudo/sudo-install-git
@@ -1,31 +1,31 @@
 #!/usr/bin/env bash
 set -Eeu -o pipefail
 
-# Git SCM
-# https://git-scm.com/
-#
-# This currently fails if OpenSSL v1.1.1+ is installed to `/usr/local`.
-# Instead, compile Git to use the system OpenSSL in `/bin/`.
-#
+# Install Git SCM.
+# Modified 2019-06-18.
+
 # See also:
+# - https://git-scm.com/
 # - https://github.com/git/git
 # - https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
 # - https://github.com/git/git/blob/master/INSTALL
 # - https://github.com/progit/progit2/blob/master/book/01-introduction/sections/installing.asc
+
+# This currently fails if OpenSSL v1.1.1+ is installed to `/usr/local`.
+# Instead, compile Git to use the system OpenSSL in `/bin/`.
 
 # shellcheck source=/dev/null
 source "${KOOPA_DIR}/include/os/fedora/sudo.sh"
 
 prefix="$KOOPA_PREFIX"
 build_name="$KOOPA_OS_BUILD_STRING"
-build_dir="${KOOPA_TMP_DIR}/build/git"
+tmp_dir="${KOOPA_TMP_DIR}/git"
+version="$(koopa variable git)"
 
-version="$(koopa_version git)"
-
-echo "Installing git ${version}."
+printf "Installing git %s.\n" "$version"
 
 # Install build dependencies.
-sudo -n yum-builddep -y git
+sudo yum-builddep -y git
 
 # This is required for git to make doc cleanly.
 #
@@ -39,22 +39,21 @@ sudo -n yum-builddep -y git
 # We're assuming Red Hat here.
 #
 # EPEL7 must be enabled for this to install (e.g. on Amazon Linux 2).
-sudo -n yum install -y docbook2X
+sudo yum install -y docbook2X
 
 # This step is required to fix a binary name difference.
 if [[ ! -f /usr/bin/docbook2x-texi ]]
 then
-    sudo -n ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
+    sudo ln -s /usr/bin/db2x_docbook2texi /usr/bin/docbook2x-texi
 fi
 
-# SC2103: Use a ( subshell ) to avoid having to cd back.
 (
-    rm -rf "$build_dir"
-    mkdir -p "$build_dir"
-    cd "$build_dir" || return 1
+    rm -rf "$tmp_dir"
+    mkdir -p "$tmp_dir"
+    cd "$tmp_dir" || exit 1
     wget "https://github.com/git/git/archive/v${version}.tar.gz"
     tar -zxf "v${version}.tar.gz"
-    cd "git-${version}" || return 1
+    cd "git-${version}" || exit 1
     # The compilation settings here are from the Git SCM book website.
     # Refer also to INSTALL file for details.
     make configure
@@ -63,13 +62,11 @@ fi
         --prefix="$prefix" \
         --with-openssl="/bin/openssl"
     make all doc info
-    sudo -n make install install-doc install-html install-info
-    rm -rf "$build_dir"
+    sudo make install install-doc install-html install-info
+    rm -rf "$tmp_dir"
 )
 
-# Ensure ldconfig is current.
-sudo -n ldconfig
+sudo ldconfig
 
-echo "git installed successfully."
 command -v git
 git --version
