Improve argument parsing

diff --git a/bin/fastq-to-fasta b/bin/fastq-to-fasta
--- a/bin/fastq-to-fasta
+++ b/bin/fastq-to-fasta
@@ -36,7 +36,7 @@ target_dir="."
 usage() {
 cat << EOF
 $(_koopa_help_header)
-    [--source-dir="."] [--target-dir="."]
+    [--source-dir="${source_dir}"] [--target-dir="${target_dir}"]
 
 Convert FASTQ files to FASTA format.
 
@@ -72,32 +72,38 @@ examples:
 
 note:
     Bash script.
-    Updated 2019-09-21.
+    Updated 2019-09-26.
 EOF
 }
 
+_koopa_help "$@"
 
 
-# Parse arguments                                                           {{{1
+
+# Arguments                                                                 {{{1
 # ==============================================================================
 
-for i in "$@"
+while (("$#"))
 do
-    case "$i" in
-        --help|-h)
-            usage
-            exit 0
-            ;;
+    case "$1" in
         --source-dir=*)
-            source_dir="${i#*=}"
-            shift
+            source_dir="${1#*=}"
+            shift 1
+            ;;
+        --source-dir)
+            source_dir="$2"
+            shift 2
             ;;
         --target-dir=*)
-            target_dir="${i#*=}"
-            shift
+            target_dir="${1#*=}"
+            shift 1
+            ;;
+        --target-dir)
+            target_dir="$2"
+            shift 2
             ;;
         *)
-            >&2 printf "Error: Invalid argument: '%s'\n" "$i"
+            >&2 printf "Error: Invalid argument: '%s'\n" "$1"
             exit 1
             ;;
     esac
@@ -126,11 +132,10 @@ then
 fi
 
 # Create the target directory automatically.
-mkdir -p "$target_dir"
+mkdir -pv "$target_dir"
 
-for i in "${array[@]}"
+for fastq_file in "${array[@]}"
 do
-    fastq_file="$1"
     fasta_file="${fastq_file//fastq/fasta}"
     paste - - - - < "$fastq_file" | \
         cut -f 1,2 | \
diff --git a/bin/run-kallisto b/bin/run-kallisto
--- a/bin/run-kallisto
+++ b/bin/run-kallisto
@@ -28,7 +28,7 @@ output_dir="kallisto/"
 usage() {
 cat << EOF
 $(_koopa_help_header)
-    --fasta-file --index-file
+    --fasta-file="FASTA" --index-file="INDEX"
     [--fastq-dir="${fastq_dir}"] [--output-dir="${output_dir}"]
 
 Run kallisto on multiple samples.
@@ -100,7 +100,7 @@ examples:
 
 note:
     Bash script.
-    Updated 2019-09-25.
+    Updated 2019-09-26.
 EOF
 }
 
@@ -112,27 +112,43 @@ _koopa_help "$@"
 # Parse arguments                                                           {{{1
 # ==============================================================================
 
-for i in "$@"
+while (("$#"))
 do
-    case "$i" in
+    case "$1" in
         --fasta-file=*)
-            fasta_file="${i#*=}"
-            shift
+            fasta_file="${1#*=}"
+            shift 1
+            ;;
+        --fasta-file)
+            fasta_file="$2"
+            shift 2
             ;;
         --fastq-dir=*)
-            fastq_dir="${i#*=}"
-            shift
+            fastq_dir="${1#*=}"
+            shift 1
+            ;;
+        --fastq-dir)
+            fastq_dir="$2"
+            shift 2
             ;;
         --index-file=*)
-            index_file="${i#*=}"
-            shift
+            index_file="${1#*=}"
+            shift 1
+            ;;
+        --index-file)
+            index_file="$2"
+            shift 2
             ;;
         --output-dir=*)
-            output_dir="${i#*=}"
-            shift
+            output_dir="${1#*=}"
+            shift 1
+            ;;
+        --output-dir)
+            output_dir="$2"
+            shift 2
             ;;
         *)
-            >&2 printf "Error: Invalid argument: '%s'\n" "$i"
+            >&2 printf "Error: Invalid argument: '%s'\n" "$1"
             exit 1
             ;;
     esac
@@ -154,7 +170,7 @@ fi
 
 
 
-# Preflight checks                                                          {{{1
+# Script                                                                    {{{1
 # ==============================================================================
 
 _koopa_assert_is_installed kallisto
@@ -163,10 +179,8 @@ _koopa_assert_is_not_dir "$output_dir"
 
 kallisto version
 
-
-
-# Sample array from FASTQ files                                             {{{1
-# ==============================================================================
+# Sample array from FASTQ files                                             {{{2
+# ------------------------------------------------------------------------------
 
 # Create a per-sample array from the R1 FASTQ files.
 array=()
@@ -188,10 +202,8 @@ fi
 
 printf "%d samples detected.\n" "${#array[@]}"
 
-
-
-# Index                                                                     {{{1
-# ==============================================================================
+# Index                                                                     {{{2
+# ------------------------------------------------------------------------------
 
 mkdir -pv "$output_dir"
 
@@ -203,10 +215,8 @@ then
     kallisto index -i "$index_file" "$fasta_file"
 fi
 
-
-
-# Quantify                                                                  {{{1
-# ==============================================================================
+# Quantify                                                                  {{{2
+# ------------------------------------------------------------------------------
 
 # Loop across the per-sample array and quantify.
 for x in "${array[@]}"
diff --git a/bin/run-salmon b/bin/run-salmon
--- a/bin/run-salmon
+++ b/bin/run-salmon
@@ -10,6 +10,7 @@ source "$(koopa header bash)"
 # ==============================================================================
 
 # Note that bcbio currently uses 30 bootstraps.
+# Uma's nextflow script currently uses 100 for kallisto.
 bootstraps=30
 threads="$CPU_COUNT"
 
@@ -27,7 +28,7 @@ output_dir="salmon/"
 usage() {
 cat << EOF
 $(_koopa_help_header)
-    --fasta-file --index-file
+    --fasta-file="FASTA" --index-file="INDEX"
     [--fastq-dir="${fastq_dir}"] [--output-dir="${output_dir}"]
 
 Run salmon on multiple samples.
@@ -91,7 +92,7 @@ see also:
 
 note:
     Bash script.
-    Updated 2019-09-25.
+    Updated 2019-09-26.
 EOF
 }
 
@@ -100,31 +101,46 @@ _koopa_help "$@"
 
 
 
-# Parse arguments                                                           {{{1
+# Arguments                                                                 {{{1
 # ==============================================================================
 
-for i in "$@"
+while (("$#"))
 do
-    case "$i" in
+    case "$1" in
         --fasta-file=*)
-            fasta_file="${i#*=}"
-            shift
+            fasta_file="${1#*=}"
+            shift 1
+            ;;
+        --fasta-file)
+            fasta_file="$2"
+            shift 2
             ;;
         --fastq-dir=*)
-            fastq_dir="${i#*=}"
-            shift
+            fastq_dir="${1#*=}"
+            shift 1
+            ;;
+        --fastq-dir)
+            fastq_dir="$2"
+            shift 2
             ;;
         --index-file=*)
-            index_file="${i#*=}"
-            shift
+            index_file="${1#*=}"
+            shift 1
+            ;;
+        --index-file)
+            index_file="$2"
+            shift 2
             ;;
         --output-dir=*)
-            output_dir="${i#*=}"
-            shift
+            output_dir="${1#*=}"
+            shift 1
+            ;;
+        --output-dir)
+            output_dir="$2"
+            shift 2
             ;;
         *)
-            # Invalid argument.
-            >&2 printf "Error: Invalid arg: '%s'\n" "$i"
+            >&2 printf "Error: Invalid argument: '%s'\n" "$1"
             exit 1
             ;;
     esac
@@ -146,18 +162,17 @@ fi
 
 
 
-# Preflight checks                                                          {{{1
+# Script                                                                    {{{1
 # ==============================================================================
 
 _koopa_assert_is_dir "$fastq_dir"
 _koopa_assert_is_not_dir "$output_dir"
 _koopa_assert_is_installed salmon
+
 salmon --version
 
-
-
-# Sample array from FASTQ files                                             {{{1
-# ==============================================================================
+# Sample array from FASTQ files                                             {{{2
+# ------------------------------------------------------------------------------
 
 # Create a per-sample array from the R1 FASTQ files.
 array=()
@@ -179,10 +194,8 @@ fi
 
 printf "%d samples detected.\n" "${#array[@]}"
 
-
-
-# Index                                                                     {{{1
-# ==============================================================================
+# Index                                                                     {{{2
+# ------------------------------------------------------------------------------
 
 mkdir -pv "$output_dir"
 
@@ -198,10 +211,8 @@ then
         -t "$fasta_file"
 fi
 
-
-
-# Quantify                                                                  {{{1
-# ==============================================================================
+# Quantify                                                                  {{{2
+# ------------------------------------------------------------------------------
 
 # Loop across the per-sample array and quantify with kallisto.
 for x in "${array[@]}"
@@ -213,13 +224,13 @@ do
     fastq_r1="${fastq_dir}/${x}${r1_tail}"
     fastq_r2="${fastq_dir}/${x}${r2_tail}"
     salmon quant \
-        --output="$sample_output_dir" \
-        --libType="A" \
-        --index="$index_file" \
-        --threads="$threads" \
-        --numBootstraps="$bootstraps" \
         --gcBias \
-        --seqBias \
+        --index="$index_file" \
+        --libType="A" \
         --mates1="$fastq_r1" \
-        --mates2="$fastq_r2"
+        --mates2="$fastq_r2" \
+        --numBootstraps="$bootstraps" \
+        --output="$sample_output_dir" \
+        --seqBias \
+        --threads="$threads"
 done
