Update scripts

diff --git a/bin/fastq-dump-from-sra-list b/bin/fastq-dump-from-sra-list
--- a/bin/fastq-dump-from-sra-list
+++ b/bin/fastq-dump-from-sra-list
@@ -2,23 +2,22 @@
 set -Eeu -o pipefail
 
 # FASTQ dump from Sequence Read Archive (SRA) accession list.
+# Modified 2019-06-18.
 
-# TODO Need to allow the user to pass arguments to fastq-dump here.
 # Consider using --`split-3` instead of `--split-files` by default.
 
 # 10X Genomics Cell Ranger data
 # https://kb.10xgenomics.com/hc/en-us/articles/115003802691
 
-# This script requires sra-tools.
-# https://github.com/ncbi/sra-tools
-command -v fastq-dump >/dev/null 2>&1 || {
-    >&2 echo "fastq-dump missing."
-    exit 1
-}
+# shellcheck source=/dev/null
+source "${KOOPA_DIR}/include/shell/bash/functions.sh"
+
+assert_is_installed fastq-dump
 
 filelist="SRR_Acc_List.txt"
-if [[ ! -f "$filelist" ]]; then
-    >&2 echo "${filelist} does not exist."
+if [[ ! -f "$filelist" ]]
+then
+    >&2 printf "%s missing.\n" "$filelist"
     exit 1
 fi
 
@@ -27,9 +26,11 @@ fi
 # Note that this will skip FASTQ files that have already been extracted.
 # This is useful because fastq-dump can take a long time and get interrupted.
 # SC2162: read without -r will mangle backslashes.
-while read -r id; do
-    if [[ ! -f "${id}.fastq.gz" ]] && [[ ! -f "${id}_1.fastq.gz" ]]; then
-        echo "SRA Accession: ${id}"
+while read -r id
+do
+    if [[ ! -f "${id}.fastq.gz" ]] && [[ ! -f "${id}_1.fastq.gz" ]]
+    then
+        printf "SRA Accession: %s.\n" "$id"
         fastq-dump --gzip --split-files "${id}"
     fi
 done < "$filelist"
diff --git a/bin/install-bcbio b/bin/install-bcbio
--- a/bin/install-bcbio
+++ b/bin/install-bcbio
@@ -2,7 +2,7 @@
 set -Eeu -o pipefail
 
 # Install bcbio-nextgen.
-# Modified 2019-06-17.
+# Modified 2019-06-18.
 
 # Use "stable" (recommended) or "development".
 # For legacy versions (e.g. v1.1.3), use bcbio-vm instead.
@@ -11,38 +11,37 @@ set -Eeu -o pipefail
 # prefix="/data00/bcbio/v1.1.5" install-bcbio
 
 prefix="${prefix:-${KOOPA_PREFIX}/bcbio}"
-build_dir="${KOOPA_TMP_DIR}/build/bcbio"
+tmp_dir="${KOOPA_TMP_DIR}/bcbio"
+version="${version:-stable}"
 
 install_dir="${prefix}/install"
 tools_dir="${prefix}/tools"
 
-version="${version:-stable}"
-
 # Ensure conda is deactivated.
 if [[ -x "$(command -v conda)" ]] && [[ -n "${CONDA_PREFIX:-}" ]]
 then
-    >&2 echo "Error: conda is active."
+    >&2 printf "Error: conda is active.\n"
     exit 1
 fi
 
 # Ensure Python virtual environment is deactivated.
 if [[ -x "$(command -v deactivate)" ]]
 then
-    >&2 echo "Error: Python virtualenv is active."
+    >&2 printf "Error: Python virtualenv is active.\n"
     exit 1
 fi
-
-prefix_mkdir "$prefix"
 
 timestamp="$(date "+%Y%m%d-%H%M%S")"
 log_dir="${HOME}/logs/${HOSTNAME}/bcbio/${version}"
 log_file="${log_dir}/bcbio-install-${version}-${timestamp}.log"
 mkdir -p "$log_dir"
 
+prefix_mkdir "$prefix"
+
 (
-    rm -rf "$build_dir"
-    mkdir -p "$build_dir"
-    cd "$build_dir"
+    rm -rf "$tmp_dir"
+    mkdir -p "$tmp_dir"
+    cd "$tmp_dir"
     wget https://raw.github.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
     python bcbio_nextgen_install.py \
         "$install_dir" \
diff --git a/bin/install-doom-emacs b/bin/install-doom-emacs
--- a/bin/install-doom-emacs
+++ b/bin/install-doom-emacs
@@ -1,17 +1,14 @@
 #!/usr/bin/env bash
 set -Eeu -o pipefail
 
-# Doom Emacs
+# Install Doom Emacs.
+# Modified 2019-06-18.
 
-# Back up existing emacs configuration, if necessary.
-(
-    cd ~
-    if [ -d ".emacs.d" ]
-    then
-        echo "Backing up '.emacs.d/' directory."
-        mv .emacs.d .emacs.d.bak
-    fi
-)
+if [[ -d ".emacs.d" ]]
+then
+    >&2 printf "Error: '.emacs.d/' directory exists.\n"
+    exit 1
+fi
 
 git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
 ~/.emacs.d/bin/doom quickstart
diff --git a/bin/install-miniconda3 b/bin/install-miniconda3
--- a/bin/install-miniconda3
+++ b/bin/install-miniconda3
@@ -1,9 +1,12 @@
 #!/usr/bin/env bash
 set -Eeu -o pipefail
 
-# Install Miniconda
-# https://conda.io/miniconda.html
-#
+# Install Miniconda.
+# Modified 2019-06-18.
+
+# See also:
+# - https://conda.io/miniconda.html
+
 # Useful script flags:
 # > bash Miniconda3-latest-Linux-x86_64.sh -h
 # -b           run install in batch mode (without manual intervention),
@@ -18,31 +21,35 @@ set -Eeu -o pipefail
 # shellcheck source=/dev/null
 source "${KOOPA_DIR}/include/shell/bash/functions.sh"
 
-prefix="${prefix:-${KOOPA_PREFIX}/miniconda3}"
-build_dir="${KOOPA_TMP_DIR}/build/miniconda3"
+prefix="${KOOPA_PREFIX}/miniconda3"
+tmp_dir="${KOOPA_TMP_DIR}/miniconda3"
 
 case "$OSTYPE" in
-    linux-gnu) script="Miniconda3-latest-Linux-x86_64.sh";;
-      darwin*) script="Miniconda3-latest-MacOSX-x86_64.sh";;
-            *) echo "${OSTYPE} is not supported."; exit 1;;
+    linux-gnu)
+        script="Miniconda3-latest-Linux-x86_64.sh"
+        ;;
+    darwin*)
+        script="Miniconda3-latest-MacOSX-x86_64.sh"
+        ;;
+    *)
+        printf "Error: %s is not supported." "$OSTYPE"
+        exit 1
+        ;;
 esac
 
 prefix_mkdir "$prefix"
 
 (
-    rm -rf "$build_dir"
-    mkdir -p "$build_dir"
-    cd "$build_dir"
-    echo "Downloading Miniconda installer."
+    rm -rf "$tmp_dir"
+    mkdir -p "$tmp_dir"
+    cd "$tmp_dir"
     curl -O "https://repo.continuum.io/miniconda/${script}"
-    # Note that this script should not be run as root.
     bash "$script" -bf -p "$prefix"
-    rm -rf "$build_dir"
+    rm -rf "$tmp_dir"
 )
 
 prefix_chgrp "$prefix"
 
-echo "conda installed successfully."
 conda_exe="${prefix}/bin/conda"
-echo "$conda_exe"
-sh -c "$conda_exe --version"
+command -v "$conda_exe"
+"$conda_exe --version"
diff --git a/bin/install-spacemacs b/bin/install-spacemacs
--- a/bin/install-spacemacs
+++ b/bin/install-spacemacs
@@ -1,23 +1,18 @@
 #!/usr/bin/env bash
 set -Eeu -o pipefail
 
-# Back up existing emacs configuration, if necessary.
-(
-    cd ~
-    if [ -d ".emacs.d" ]
-    then
-        echo "Backing up '.emacs.d/' directory."
-        mv .emacs.d .emacs.d.bak
-    fi
-)
+# Install spacemacs.
+# Modified 2019-06-18.
 
-# Now we're ready to install spacemacs.
-echo "Cloning spacemacs repo."
+if [[ -d ".emacs.d" ]]
+then
+    >&2 printf "Error: '.emacs.d/' directory exists.\n"
+    exit 1
+fi
+
 git clone git@github.com:syl20bnr/spacemacs.git ~/.emacs.d
 
-# Fix org-projectile warning
-# Error (use-package): org-projectile :config: Symbol's function definition is
-# void: org-projectile-per-project
-rm -f ~/.emacs.d/elpa/org-projectile-*/org-projectile.elc
-
 emacs
+
+# Fix for org-projectile warning.
+# > rm -f ~/.emacs.d/elpa/org-projectile-*/org-projectile.elc
