Harden find and replace for slashes

diff --git a/bin/find-and-replace b/bin/find-and-replace
--- a/bin/find-and-replace
+++ b/bin/find-and-replace
@@ -6,11 +6,17 @@ set -Eeuo pipefail
 pattern="$1"
 replacement="$2"
 
-if [[ -n "${MACOS:-}" ]]
+# Check for unescaped slashes.
+if echo "$pattern" | grep -q '/' &&
+    echo "$pattern" | grep -Fqv '\'
 then
-    find . -type f -exec sed -i "s/${pattern}/${replacement}/g" {} \;
-elif [[ -n "${LINUX:-}" ]]
-then
-    # Note the extra quotes in sed command here.
-    find . -type f -exec sed -i "" "s/${pattern}/${replacement}/g" {} \;
+    >&2 echo "Error: Unescaped '/' detected in pattern."
 fi
+
+if echo "$replacement" | grep -q '/' &&
+    echo "$replacement" | grep -Fqv '\'
+then
+    >&2 echo "Error: Unescaped '/' detected in replacement."
+fi
+
+find . -type f -exec sed -i "s/${pattern}/${replacement}/g" {} \;
