Improve FTP mirror documentation

diff --git a/bin/ftp-mirror b/bin/ftp-mirror
--- a/bin/ftp-mirror
+++ b/bin/ftp-mirror
@@ -4,23 +4,16 @@ set -Eeu -o pipefail
 # shellcheck source=/dev/null
 source "$(koopa header bash)"
 
-# Recursively download (mirror) over FTP using wget.
-# Updated 2019-07-30.
-
-# For secure transfers, just use rsync or scp instead.
-
-_koopa_assert_is_installed wget
-
 
 
 # Usage                                                                     {{{1
 # ==============================================================================
 
-# FIXME Rework to use "=" on long flags here.
-
 usage() {
     cat << EOF
-usage: ftp-mirror [-h] --host "HOSTNAME" --user "USERNAME" [--dir "REMOTE DIR"]
+usage: ftp-mirror [-h] --host="HOST" --user="USER" [--dir="DIR"]
+
+Recursively download (mirror) over FTP using wget.
 
 required arguments:
     --host
@@ -35,6 +28,13 @@ optional arguments:
     --dir
         Remote directory path. Note that this script always mirrors to the
         current working directory path on the local machine.
+
+details:
+    For secure transfers, just use rsync or scp instead.
+
+note:
+    Bash script.
+    Updated 2019-07-30.
 EOF
 }
 
@@ -43,20 +43,20 @@ EOF
 # Parse arguments                                                           {{{1
 # ==============================================================================
 
-while (("$#"))
+for i in "$@"
 do
-    case "$1" in
-        -h|--help)
+    case "$i" in
+        --help|-h)
             usage
             exit 0
             ;;
-        --host)
-            host="$2"
-            shift 2
+        --host=*)
+            host="${i#*=}"
+            shift
             ;;
-        --user)
-            user="$2"
-            shift 2
+        --user=*)
+            user="${i#*=}"
+            shift
             ;;
         --)
             # End argument parsing.
@@ -64,8 +64,8 @@ do
             break
             ;;
         --*|-*)
-            # Unsupported flags.
-            >&2 printf "Error: Invalid flag '%s'\n" "$1"
+            # Invalid argument.
+            >&2 printf "Error: Invalid argument: '%s'\n" "$i"
             exit 1
             ;;
         *)
@@ -77,17 +77,17 @@ done
 if [[ -z "${host:-}" ]] ||
     [[ -z "${user:-}" ]]
 then
-    >&2 printf "Error: Missing required argument.\n\n"
+    >&2 printf "Error: Missing argument.\n\n"
     usage
     exit 1
 fi
 
-unset -f usage
 
 
-
-# Run script                                                                {{{1
+# Script                                                                    {{{1
 # ==============================================================================
+
+_koopa_assert_is_installed wget
 
 if [[ -n "${dir:-}" ]]
 then
@@ -96,7 +96,4 @@ else
     path="${host}"
 fi
 
-wget \
-    --ask-password \
-    --mirror \
-    "ftp://${user}@${path}/"*
+wget --ask-password --mirror "ftp://${user}@${path}/"*
