Improve documentation

diff --git a/bin/git-pull-recursive b/bin/git-pull-recursive
--- a/bin/git-pull-recursive
+++ b/bin/git-pull-recursive
@@ -4,10 +4,55 @@ set -Eeu -o pipefail
 # shellcheck source=/dev/null
 source "$(koopa header bash)"
 
-# Pull all git repositories recursively.
-# Updated 2019-06-23.
+
+
+# Usage                                                                     {{{1
+# ==============================================================================
+
+usage() {
+cat << EOF
+usage: git-pull-recursive [--help|-h] [DIR="."]
+
+Pull all git repositories recursively.
+
+optional positional arguments:
+    1.  Directory path.
+        Defaults to current working directory.
+
+optional arguments:
+    --help, -h
+        Show this help message and exit.
+
+note:
+    Bash script.
+    Updated 2019-06-23.
+EOF
+}
+
+
+
+# Parse arguments                                                           {{{1
+# ==============================================================================
+
+case "${1:-}" in
+    "")
+        ;;
+    --help|-h)
+        usage
+        exit
+        ;;
+    *)
+        >&2 printf "Error: Unsupported argument: '%s'\n" "$1"
+        exit 1
+        ;;
+esac
 
 git_dir="${1:-.}"
+
+
+
+# Script                                                                    {{{1
+# ==============================================================================
 
 # SC2044: For loops over find output are fragile.
 # Using `-L` flag here in case git dir is a symlink.
@@ -22,5 +67,3 @@ do
         git status
     )
 done <   <(find -L "$git_dir" -maxdepth 2 -type d -name ".git" -print0)
-
-unset -v git_dir
