Prepare release

diff --git a/bin/install-anaconda3 b/bin/install-anaconda3
--- a/bin/install-anaconda3
+++ b/bin/install-anaconda3
@@ -5,7 +5,7 @@ set -Eeuo pipefail
 # https://www.anaconda.com/download
 # https://docs.anaconda.com/anaconda/install/
 
-prefix="${KOOPA_PREFIX}/anaconda3"
+prefix="${HOME}/anaconda3"
 build_dir="${KOOPA_TMP}/build/anaconda3"
 
 version="2019.03"
@@ -19,8 +19,13 @@ case "$OSTYPE" in
             *) echo "${OSTYPE} is not supported."; exit 1;;
 esac
 
-# Ensure previous installation is removed.
-sudo rm -rf "$prefix"
+# Check for previous installation.
+if [[ -d "$prefix" ]]
+then
+    echo "Error: conda already installed."
+    echo "$prefix"
+    exit 1
+fi
 
 (
     rm -rf "$build_dir"
@@ -32,9 +37,6 @@ sudo rm -rf "$prefix"
     bash "$script" -b -p "$prefix"
     rm -rf "$build_dir"
 )
-
-# Set installed files to root.
-sudo chown -R "root:wheel" "$prefix"
 
 echo "Reloading the current shell."
 exec "$KOOPA_SHELL"
