Improve virtualenv detection

diff --git a/bin/install-python-virtualenv b/bin/install-python-virtualenv
--- a/bin/install-python-virtualenv
+++ b/bin/install-python-virtualenv
@@ -7,7 +7,28 @@ set -Eeuxo pipefail
 command -v python
 command -v virtualenv
 
-env_dir="${HOME}/.virtualenvs"
-env_name="default"
+# Ensure virtualenv is deactivated.
+if [[ -x "$(command -v deactivate)" ]]
+then
+    echo "Error: virtualenv is active." >&2
+    exit 1
+fi
 
-virtualenv "${env_dir}/${env_name}" --system-site-packages
+env_base_dir="${HOME}/.virtualenvs"
+
+env_name="$1"
+if [[ -z "${env_name:-}" ]]
+then
+    env_name="default"
+fi
+
+env_dir="${env_base_dir}/${env_name}"
+rm -rf "$env_dir"
+
+# Python 2 method (deprecated)
+# > virtualenv "$env_dir" --system-site-packages
+
+python3 -m venv "$env_dir"
+
+echo "Python ${env_name} virtual environment installed successfully."
+echo "Source the 'activate' binary in your current shell session to activate."
