Improve doom emacs install script

diff --git a/bin/install-doom-emacs b/bin/install-doom-emacs
--- a/bin/install-doom-emacs
+++ b/bin/install-doom-emacs
@@ -5,13 +5,15 @@ set -Eeu -o pipefail
 source "$(koopa header bash)"
 
 # Install Doom Emacs.
-# Updated 2019-06-23.
+# Updated 2019-09-19.
 
-if [[ -d ".emacs.d" ]]
+install_dir="${HOME}/.emacs.d"
+
+if [[ -d "$install_dir" ]]
 then
-    >&2 printf "Error: '.emacs.d/' directory exists.\n"
+    >&2 printf "Error: Directory exists: '%s'.\n" "$install_dir"
     exit 1
 fi
 
-git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
-~/.emacs.d/bin/doom quickstart
+git clone https://github.com/hlissner/doom-emacs "$install_dir"
+"${install_dir}/bin/doom" quickstart
