Add documentation

diff --git a/bin/move-into-dated-dirs-by-timestamp b/bin/move-into-dated-dirs-by-timestamp
--- a/bin/move-into-dated-dirs-by-timestamp
+++ b/bin/move-into-dated-dirs-by-timestamp
@@ -4,12 +4,41 @@ set -Eeu -o pipefail
 # shellcheck source=/dev/null
 source "$(koopa header bash)"
 
-# Move files into dated subdirectories by timestamp.
-# Updated 2019-07-28.
 
-[[ -z "${1:-}" ]] &&
-    printf "Error: No files were specified.\n" &&
+
+# Usage                                                                     {{{1
+# ==============================================================================
+
+usage() {
+cat << EOF
+move-into-dated-dirs-by-timestamp [--help|-h] files ...
+
+Move files into dated subdirectories by timestamp.
+
+required positional arguments:
+    ... File paths.
+        Assuming we're matching inside current working directory.
+
+optional arguments:
+    --help, -h
+        Show this help message and exit.
+
+note:
+    Bash script.
+    Updated 2019-07-28.
+EOF
+}
+
+
+
+# Script                                                                    {{{1
+# ==============================================================================
+
+if [[ -z "${1:-}" ]]
+then
+    >&2 printf "Error: No files were specified.\n"
     exit 1
+fi
 
 for file in "$@"
 do
