Add documentation

diff --git a/bin/move-into-dated-dirs-by-filename b/bin/move-into-dated-dirs-by-filename
--- a/bin/move-into-dated-dirs-by-filename
+++ b/bin/move-into-dated-dirs-by-filename
@@ -4,22 +4,53 @@ set -Eeu -o pipefail
 # shellcheck source=/dev/null
 source "$(koopa header bash)"
 
-# Move files into dated subdirectories by file name.
-# Updated 2019-07-28.
 
-# Useful for organizing photos, scans, and videos.
 
-# Examples:
-# - 20190101_010101_0001.mov
-# - 2019-01-01-01-01-01.pdf
+# Usage                                                                     {{{1
+# ==============================================================================
 
-# Ensure we're escaping spaces correctly.
-# See also:
-# - https://unix.stackexchange.com/questions/9496
+usage() {
+cat << EOF
+usage: move-into-dated-dirs-by-filename [--help|-h] files ...
 
-[[ -z "${1:-}" ]] &&
-    printf "Error: No files were specified.\n" &&
+Move files into dated subdirectories by file name.
+
+required positional arguments:
+    ... File paths.
+        Assuming we're matching inside current working directory.
+
+optional arguments:
+    --help, -h
+        Show this help message and exit.
+
+details:
+    Useful for organizing photos, scans, and videos.
+
+examples:
+    - 20190101_010101_0001.mov
+    - 2019-01-01-01-01-01.pdf
+
+see also:
+    https://unix.stackexchange.com/questions/9496
+
+note:
+    Bash script.
+    Updated 2019-07-28.
+EOF
+}
+
+_koopa_help "$@"
+
+
+
+# Script                                                                    {{{1
+# ==============================================================================
+
+if [[ -z "${1:-}" ]]
+then
+    >&2 printf "Error: No files were specified.\n"
     exit 1
+fi
 
 grep_array=(
     '([0-9]{4})'
