Update scripts

diff --git a/bin/strict-mode b/bin/strict-mode
--- a/bin/strict-mode
+++ b/bin/strict-mode
@@ -1,6 +1,7 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
-# Make bash stricter by default using set built-in.
+# Make shell stricter by default using set built-in.
+# Modified 2019-06-18.
 
 # See also:
 # - https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
@@ -9,28 +10,24 @@
 # - https://github.com/anordal/shellharden/blob/master/how_to_do_things_safely_in_bash.md#how-to-begin-a-bash-script
 # - https://github.com/manubot/rootstock/pull/233
 
-# NOTE: Do not attempt to use this in `~/.bash_profile` for a remote SSH server,
-# as unbound variables will cause the login to fail and you can get locked out.
+# NOTE: Do not attempt to use this in `~/.shrc` for a remote SSH server, as
+# unbound variables will cause the login to fail and you can get locked out.
 # Only attempt to ever enable this mode on a local machine, where you can
 # disable strict mode easily.
 
-# For scripts, this one-liner can be placed under the shebang line:
-# $ set -Eeu -o pipefail
+# For bash scripts, this one-liner can be placed under the shebang line. Take
+# out the `-E` flag for zsh.
+# > set -Eeu -o pipefail
 
 
 
 # Exit immediately when a command fails.
-# $ set -e
+# > set -e
 set -o errexit
 
-# Catch ERR traps properly, which won't fire in certain scenarios for `-e` flag.
-# $ set -E
-set -o errtrace
-
 # Treat unset variables as an error and exit immediately.
-# NOTE: Bash 4.3 earlier can have issues with this setting.
-# See: https://github.com/anordal/shellharden/blob/master/how_to_do_things_safely_in_bash.md#how-to-begin-a-bash-script
-# $ set -u
+# NOTE: Bash <= 4.3 can have issues with this setting.
+# > set -u
 set -o nounset
 
 # The bash shell normally only looks at the exit code of the last command of a
@@ -43,8 +40,15 @@ set -o pipefail
 
 # Print each command before executing. This command is great for scripts but too
 # noisy when added to bash_profile, and is not generally recommended here.
-# $ set -x
-# $ set -o xtrace
+# > set -x
+# > set -o xtrace
+
+if [ "$KOOPA_SHELL" = "bash" ]
+then
+    # Catch ERR traps properly, which won't fire in certain scenarios for `-e` flag.
+    # > set -E
+    set -o errtrace
+fi
 
 
 
@@ -59,6 +63,6 @@ set -o pipefail
 # - nullglob: If set, bash allows patterns which match no files (see Pathname
 #   Expansion above) to expand to a null string, rather than themselves.
 #
-# $ shopt -s failglob
-# $ shopt -s globstar
-# $ shopt -s nullglob
+# > shopt -s failglob
+# > shopt -s globstar
+# > shopt -s nullglob
