Draft update of tldr

diff --git a/bin/tldr b/bin/tldr
--- a/bin/tldr
+++ b/bin/tldr
@@ -1,133 +1,44 @@
-#!/bin/sh
-# tldr client by Ray Lee, http://github.com/raylee/tldr
-# a Sunday afternoon's project, I'm sure there's room for improvement. PRs welcome!
+#!/usr/bin/env bash
 
-set -uf
-# next only works on some shells, check for support before trying to set the feature
-set -o | grep -q pipefail && set -o pipefail 2>/dev/null
+KOOPA_PREFIX="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
+    >/dev/null 2>&1 && pwd -P)"
+# shellcheck source=/dev/null
+source "${KOOPA_PREFIX}/shell/bash/include/header.sh"
 
-# initialize globals, sanity check the environment, etc.
-config() {
-    init_term_cmds
+# The portable way to disable filename expansion.
+set -f
 
-    if [ -z "$(command -v curl)" ]; then
-        echo "${red}tldr requires \`curl\` installed in your path${reset}"
-        exit 1
-    fi
-    configdir=~/.tldr
-    [ -d ~/.config ] && configdir=~/.config/tldr
+set -x
 
-    platform=$(get_platform)
-    base_url="https://raw.githubusercontent.com/tldr-pages/tldr/master/pages"
-    index_url="https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/master/assets/index.json"
-    index="$configdir/index.json"
-    cache_days=14
-    force_update=''
+# """
+# Modified version of tldr client by Ray Lee
+# http://github.com/raylee/tldr
+# """
 
-    #check if config folder exists, otherwise create it
-    if [ ! -d "$configdir" ]; then
-        mkdir -p "$configdir"
-        cache_tldr
-    fi
+_koopa_assert_is_installed curl tput
 
-    [ ! -f $index ] && update_index
-    auto_update_index
-}
 
-update_index() {
-    curl -sf -o "$index" "$index_url"
-    res=$?
-    if [ $res -eq 22 ]; then
-        echo "Could not download index from $index_url"
-        exit 1
-    fi
-}
 
-# if the file exists and is more recent than $cache_days old
-recent() {
-    exists=$(find "$1" -mtime -$cache_days 2>/dev/null)
-    [ -n "$exists" -a -z "$force_update" ]
-}
+# Functions  {{{1
+# ==============================================================================
 
 auto_update_index() {
     recent "$index" || update_index
 }
 
+# FIXME Can we just use basename here?
 bname() {
     fn=${1##*/}
     fn=${fn%$2}
     printf "%s\n" "$fn"
 }
 
-style_for() {
-    style=""
-    # sanitize user input, only lowercase and spaces are allowed
-    for i in $(printf %s "$*" | tr -cd '[a-z] '); do
-        eval t=\$$i
-        style="${style}$t"
-    done
-    printf %s "$style"
-}
-
-# function contents via http://mywiki.wooledge.org/BashFAQ/037
-init_term_cmds() {
-    true && {
-        reset=$(    tput sgr0   || tput me      ) # Reset cursor
-        bold=$(     tput bold   || tput md      ) # Start bold
-        underline=$(tput smul   || tput us      ) # Start underline
-        italic=$(   tput sitm   || tput ZH      ) # Start italic
-        eitalic=$(  tput ritm   || tput ZH      ) # End italic
-        default=$(  tput op                     )
-        back=$(     printf '\b' )
-
-        case "$TERM" in
-            *-m) ;;
-            *)
-                black=$(    tput setaf 0 || tput AF 0    )
-                red=$(      tput setaf 1 || tput AF 1    )
-                green=$(    tput setaf 2 || tput AF 2    )
-                yellow=$(   tput setaf 3 || tput AF 3    )
-                blue=$(     tput setaf 4 || tput AF 4    )
-                magenta=$(  tput setaf 5 || tput AF 5    )
-                cyan=$(     tput setaf 6 || tput AF 6    )
-                white=$(    tput setaf 7 || tput AF 7    )
-
-                onblue=$(   tput setab 4 || tput AB 4    )
-                ongrey=$(   tput setab 7 || tput AB 7    )
-                ;;
-        esac
-    } 2>/dev/null
-
-    # osx's termcap doesn't have italics. The below adds support for iTerm2
-    # and is harmless on Terminal.app
-    [ "$(get_platform)" = "osx" ] && {
-        italic=$(printf "\033[3m")
-        eitalic=$(printf "\033[23m")
-    }
-
-    # custom styling if set in environment variables
-    sheader=$(style_for ${TLDR_HEADER:-red})
-    squote=$(style_for ${TLDR_QUOTE:-underline})
-    sdescription=$(style_for ${TLDR_DESCRIPTION:-reset})
-    scode=$(style_for ${TLDR_CODE:-bold})
-    sparam=$(style_for ${TLDR_PARAM:-italic})
-    eparam=$(style_for ${TLDR_EPARAM:-eitalic})
-}
-
-heading() {
-    printf "%s\n" "${sheader}${*#??}$reset"
-}
-
-quotation() {
-    echo "${squote}${*#??}$reset"
-}
-
-list_item() {
-    echo "${sdescription}$*$reset"
-}
-
-style_params() {
-    printf %s "$*" | sed "s/{{/${sparam}/g;s/}}/${eparam}/g"
+# cache a local copy of the tldrpage
+cache_tldr() {
+    contains "$(tar --version | head -n 1)" bsdtar || taropt='--wildcards --overwrite'
+    curl -sfL https://github.com/tldr-pages/tldr/tarball/master \
+    | tar xzf - --strip-components=2 -C "$configdir" ${taropt-} '*/pages/'
+    update_index
 }
 
 code() {
@@ -135,12 +46,111 @@ code() {
     printf "%s\n" "$*" | sed "s/\`\([^\`]*\)\`/  ${scode}\1${reset}/g"
 }
 
-text() {
-    echo "$*"
-}
-
 contains() {
     test "${1#*$2}" != "$1"
+}
+
+fetch_tldr() {
+    curl -sf "https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/{$platform,common}/$1.md"
+}
+
+# convert the local platorm name to tldr's version
+get_platform() {
+    case $(uname -s) in
+        Darwin)                 echo "osx"    ;;
+        Linux)                  echo "linux"  ;;
+        SunOS)                  echo "sunos"  ;;
+        CYGWIN*|MINGW32*|MSYS*) echo "windows" ;;
+        *)                      echo "common" ;;
+    esac
+}
+
+# return the local cached copy of the tldrpage, or retrieve and cache from github
+get_tldr() {
+    p=$(path_for_cmd "$1")
+    cached="$configdir/$p"
+    recent "$cached" || {
+        mkdir -p $(dirname "$cached")
+        curl -sf -o "$cached" "$base_url/$p"
+    }
+    # if the curl failed for some reason, keep cat from whinging
+    cat "$cached" 2>/dev/null
+}
+
+heading() {
+    printf "%s\n" "${sheader}${*#??}$reset"
+}
+
+list_item() {
+    echo "${sdescription}$*$reset"
+}
+
+list_pages() {
+    for platform in $(ls "$configdir" )
+    do
+        for page in $(ls 2>/dev/null "$configdir"/"$platform/")
+        do
+            bname "$page" .md
+        done
+    done | sort | uniq
+}
+
+# Extract the platform key from index.json, return preferred subpath to tldrpage
+path_for_cmd() {
+    override="$configdir/local/$1.md"
+    if [ -f "$override" ]; then
+        echo "local/$1.md"
+        return
+    fi
+
+    # results in, eg, "name":"netstat","platform":["linux","osx"]},
+    desc=$(tr '{' '\n' < $index | grep "\"name\":\"$1\"")
+    [ -z "$desc" ] && echo "-- not found --" && return
+
+    # use the platform specific version of the tldr first
+    if contains $desc "$platform"; then
+        echo "$platform/$1.md"
+    elif contains $desc "common"; then
+        echo "common/$1.md"
+    else
+        # take the first one so we can show something, but warn the user
+        p=$(echo "$desc" | cut -d '"' -f 8)
+        >&2 printf "${red}tldr page $1 not found in $platform or common, using page from platform $p instead$reset\n"
+        echo "$p/$1.md"
+    fi
+}
+
+quotation() {
+    echo "${squote}${*#??}$reset"
+}
+
+# If the file exists and is more recent than '$cache_days' old.
+recent() {
+    exists="$(find "$1" -mtime "-${cache_days}" 2>/dev/null)"
+    [[ -n "$exists" ]] && [[ -z "$force_update" ]]
+}
+
+# FIXME Take this out...unnecessary.
+# FIXME Rethink the for loop approach here...
+style_for() {
+    style=""
+    # Sanitize user input. Only lowercase and spaces are allowed.
+    for i in $(printf %s "$*" | tr -cd '[a-z] ')
+    do
+        # FIXME Can we avoid the eval call here?
+        eval t="\$$i"
+        style="${style}${t}"
+    done
+    printf %s "$style"
+}
+
+
+style_params() {
+    printf %s "$*" | sed "s/{{/${sparam}/g;s/}}/${eparam}/g"
+}
+
+text() {
+    echo "$*"
 }
 
 trim() {
@@ -152,7 +162,19 @@ trim() {
     printf %s "$var"
 }
 
-# an idiot-level recognition of tldr's markdown. Needs improvement, or
+update_index() {
+    curl -sf -o "$index" "$index_url"
+    res="$?"
+    if [[ "$res" -eq 22 ]]
+    then
+        _koopa_stop "Could not download index from '${index_url}'."
+    fi
+    return 0
+}
+
+
+
+# An idiot-level recognition of tldr's markdown. Needs improvement, or
 # subcontracting out to a markdown -> ANSI formatting command
 display_tldr() {
     last_token=''
@@ -191,97 +213,92 @@ display_tldr() {
     done
 }
 
-# convert the local platorm name to tldr's version
-get_platform() {
-    case $(uname -s) in
-        Darwin)                 echo "osx"    ;;
-        Linux)                  echo "linux"  ;;
-        SunOS)                  echo "sunos"  ;;
-        CYGWIN*|MINGW32*|MSYS*) echo "windows" ;;
-        *)                      echo "common" ;;
-    esac
-}
 
-# extract the platform key from index.json, return preferred subpath to tldrpage
-path_for_cmd() {
-    override="$configdir/local/$1.md"
-    if [ -f "$override" ]; then
-        echo "local/$1.md"
-        return
-    fi
 
-    # results in, eg, "name":"netstat","platform":["linux","osx"]},
-    desc=$(tr '{' '\n' < $index | grep "\"name\":\"$1\"")
-    [ -z "$desc" ] && echo "-- not found --" && return
+# Config  {{{1
+# ==============================================================================
 
-    # use the platform specific version of the tldr first
-    if contains $desc "$platform"; then
-        echo "$platform/$1.md"
-    elif contains $desc "common"; then
-        echo "common/$1.md"
-    else
-        # take the first one so we can show something, but warn the user
-        p=$(echo "$desc" | cut -d '"' -f 8)
-        >&2 printf "${red}tldr page $1 not found in $platform or common, using page from platform $p instead$reset\n"
-        echo "$p/$1.md"
-    fi
-}
+# Contents via http://mywiki.wooledge.org/BashFAQ/037.
+reset="$(    tput sgr0   || tput me      )"  # Reset cursor
+bold="$(     tput bold   || tput md      )"  # Start bold
+underline="$(tput smul   || tput us      )"  # Start underline
 
-# cache a local copy of the tldrpage
-cache_tldr() {
-    contains "$(tar --version | head -n 1)" bsdtar || taropt='--wildcards --overwrite'
-    curl -sfL https://github.com/tldr-pages/tldr/tarball/master \
-    | tar xzf - --strip-components=2 -C "$configdir" ${taropt-} '*/pages/'
-    update_index
-}
 
-# return the local cached copy of the tldrpage, or retrieve and cache from github
-get_tldr() {
-    p=$(path_for_cmd "$1")
-    cached="$configdir/$p"
-    recent "$cached" || {
-        mkdir -p $(dirname "$cached")
-        curl -sf -o "$cached" "$base_url/$p"
-    }
-    # if the curl failed for some reason, keep cat from whinging
-    cat "$cached" 2>/dev/null
-}
+default="$(  tput op                     )"
+back="$(     printf '\b' )"
 
-fetch_tldr() {
-    curl -sf "https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/{$platform,common}/$1.md"
-}
+case "$TERM" in
+    *-m) ;;
+    *)
+        black="$(    tput setaf 0 || tput AF 0    )"
+        red="$(      tput setaf 1 || tput AF 1    )"
+        green="$(    tput setaf 2 || tput AF 2    )"
+        yellow="$(   tput setaf 3 || tput AF 3    )"
+        blue="$(     tput setaf 4 || tput AF 4    )"
+        magenta="$(  tput setaf 5 || tput AF 5    )"
+        cyan="$(     tput setaf 6 || tput AF 6    )"
+        white="$(    tput setaf 7 || tput AF 7    )"
 
-list_pages() {
-    for platform in $(ls "$configdir" ); do
-        for page in $(ls 2>/dev/null "$configdir"/"$platform/") ; do
-            bname "$page" .md
-        done
-    done | sort | uniq
-}
+        onblue="$(   tput setab 4 || tput AB 4    )"
+        ongrey="$(   tput setab 7 || tput AB 7    )"
+        ;;
+esac
 
-config
+# Italics  {{{2
+# ------------------------------------------------------------------------------
 
-usage() {
-    cmd=$(basename "$0")
-    cat <<EOF
-USAGE: $cmd [options] <command>
+# macOS termcap doesn't have italics. This adds support for iTerm2 and is
+# harmless on Terminal.app.
+if [[ "$(get_platform)" == "osx" ]]
+then
+    italic="$(printf "\033[3m")"                        # Start italic
+    eitalic="$(printf "\033[23m")"                      # End italic
+else
+    italic="$(   tput sitm   || tput ZH      )"         # Start italic
+    eitalic="$(  tput ritm   || tput ZH      )"         # End italic
+fi
 
-[options]
-    -l, --list:       show all available pages
-    -p, --platform:   show page from specific platform rather than autodetecting
-    -u, -c, --update: update, force retrieving latest copies of locally cached files
-    -h, -?, --help:   this help overview
 
-<command>
-    Show examples for this command
 
-The client caches a copy of all pages and the index locally under
-$configdir . By default, the cached copies will expire in $cache_days days.
 
-EOF
-exit 0
-}
+# FIXME JUST PASS THE VARIABLE IN DIRECTLY HERE.
+# Custom styling if set in environment variables.
+sheader="$(style_for "${TLDR_HEADER:-red}")"
+squote="$(style_for "${TLDR_QUOTE:-underline}")"
+sdescription="$(style_for "${TLDR_DESCRIPTION:-reset}")"
+scode="$(style_for "${TLDR_CODE:-bold}")"
+sparam="$(style_for "${TLDR_PARAM:-italic}")"
+eparam="$(style_for "${TLDR_EPARAM:-eitalic}")"
 
+
+
+
+# FIXME USE XDG CONFIG HERE.
+configdir=~/.tldr
+[ -d ~/.config ] && configdir=~/.config/tldr
+
+platform=$(get_platform)
+base_url="https://raw.githubusercontent.com/tldr-pages/tldr/master/pages"
+index_url="https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/master/assets/index.json"
+index="$configdir/index.json"
+cache_days=14
+force_update=''
+
+#check if config folder exists, otherwise create it
+if [ ! -d "$configdir" ]; then
+    mkdir -p "$configdir"
+    cache_tldr
+fi
+
+[ ! -f $index ] && update_index
+auto_update_index
+
+
+
+# Argument parsing  {{{1
+# ==============================================================================
+
+# FIXME Switch to other approach used in bash scripts.
 while [ $# -gt 0 ]
 do
     case "$1" in
@@ -301,12 +318,9 @@ do
             cache_tldr
             exit 0
             ;;
-        -h|-\?|--help|-*)
-            usage
-            ;;
         *)
-            # there are pages with hypens in them, such as git-tag. The below converts
-            # `tldr git tag` to the hyphenated version
+            # There are pages with hypens in them, such as 'git-tag'.
+            # This converts 'tldr git tag' to the hyphenated version.
             hyphenated=$(printf %s "$*" | tr ' ' '-')
             page=${hyphenated:-''}
             break
@@ -315,19 +329,23 @@ do
     shift
 done
 
-[ -z "${page:-}" ] && usage
 
-# if the environment variable TLDR_CACHE=no then fetch the page directly from github, otherwise use the cache
-if [ "${TLDR_CACHE-unset}" = "no" ]; then
-    tldr=$(fetch_tldr "$page")
+
+# Display tldr  {{{1
+# ==============================================================================
+
+# If the environment variable 'TLDR_CACHE=no', then fetch the page directly from
+# GitHub; otherwise, use the cache.
+if [[ "${TLDR_CACHE-unset}" == "no" ]]
+then
+    tldr="$(fetch_tldr "$page")"
 else
-    tldr=$(get_tldr "$page")
+    tldr="$(get_tldr "$page")"
 fi
 
-if [ -z "$tldr" ]; then
-    echo "tldr page for command $page not found"
-    exit 1
+if [[ -z "$tldr" ]]
+then
+    _koopa_stop "tldr page for command ${page} not found."
 fi
 
 display_tldr "$tldr"
-echo
