Draft update to tldr

diff --git a/bin/tldr b/bin/tldr
--- a/bin/tldr
+++ b/bin/tldr
@@ -5,15 +5,12 @@ KOOPA_PREFIX="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
 # shellcheck source=/dev/null
 source "${KOOPA_PREFIX}/shell/bash/include/header.sh"
 
-# The portable way to disable filename expansion.
-set -f
-
-set -x
-
 # """
 # Modified version of tldr client by Ray Lee
 # http://github.com/raylee/tldr
 # """
+
+# FIXME Don't use echo here.
 
 _koopa_assert_is_installed curl tput
 
@@ -22,144 +19,106 @@ _koopa_assert_is_installed curl tput
 # Functions  {{{1
 # ==============================================================================
 
+# Variables  {{{2
+# ------------------------------------------------------------------------------
+
+get_platform() {
+    # """
+    # Convert the local platorm name to tldr's version.
+    #
+    # @note Updated 2020-04-27.
+    #
+    # Supported tldr platforms:
+    # https://github.com/tldr-pages/tldr/tree/master/pages
+    # """
+    local str
+    case "$(uname -s)" in
+        Darwin)
+            str="osx"
+            ;;
+        Linux)
+            str="linux"
+            ;;
+        SunOS)
+            str="sunos"
+            ;;
+        CYGWIN*|MINGW32*|MSYS*)
+            str="windows"
+            ;;
+        *)
+            str="common"
+            ;;
+    esac
+    _koopa_print "$str"
+}
+
+# Caching and indexing  {{{2
+# ------------------------------------------------------------------------------
+
 auto_update_index() {
+    # """
+    # Auto-update index.
+    # @note Updated 2020-04-27.
+    # """
     recent "$index" || update_index
+    return 0
 }
 
-# FIXME Can we just use basename here?
-bname() {
-    fn=${1##*/}
-    fn=${fn%$2}
-    printf "%s\n" "$fn"
-}
-
-# cache a local copy of the tldrpage
+# FIXME Rework this.
+# FIXME On macOS this is tar --help instead of tar --version no?
+# FIXME Allow the user to recache here.
+# FIXME This attempts to set the tar flags for macOS/Linux.
 cache_tldr() {
-    contains "$(tar --version | head -n 1)" bsdtar || taropt='--wildcards --overwrite'
+    # """
+    # Cache a local copy of the tldr-pages repo.
+    #
+    # @note Updated 2020-04-27.
+    # """
+    _koopa_grepl \
+        "$(tar --version | head -n 1)" bsdtar \
+        || taropt='--wildcards --overwrite'
     curl -sfL https://github.com/tldr-pages/tldr/tarball/master \
-    | tar xzf - --strip-components=2 -C "$configdir" ${taropt-} '*/pages/'
+        | tar xzf - \
+            --strip-components=2 \
+            -C "$configdir" \
+            "${taropt-}" \
+            '*/pages/'
     update_index
-}
-
-code() {
-    # take everything between two backticks, capture it, surround it with styling
-    printf "%s\n" "$*" | sed "s/\`\([^\`]*\)\`/  ${scode}\1${reset}/g"
-}
-
-contains() {
-    test "${1#*$2}" != "$1"
+    return 0
 }
 
 fetch_tldr() {
-    curl -sf "https://raw.githubusercontent.com/tldr-pages/tldr/master/pages/{$platform,common}/$1.md"
+    # """
+    # Fetch and individual tldr page.
+    #
+    # @note Updated 2020-04-27.
+    # """
+    curl -sf "https://raw.githubusercontent.com/tldr-pages/tldr/master/\
+pages/{${platform},common}/${1}.md"
+    return 0
 }
 
-# convert the local platorm name to tldr's version
-get_platform() {
-    case $(uname -s) in
-        Darwin)                 echo "osx"    ;;
-        Linux)                  echo "linux"  ;;
-        SunOS)                  echo "sunos"  ;;
-        CYGWIN*|MINGW32*|MSYS*) echo "windows" ;;
-        *)                      echo "common" ;;
-    esac
-}
-
-# return the local cached copy of the tldrpage, or retrieve and cache from github
 get_tldr() {
-    p=$(path_for_cmd "$1")
+    # """
+    # Return the local cached copy of the tldrpage, or retrieve and cache from
+    # GitHub.
+    #
+    # @note Updated 2020-04-27.
+    # """
+    p="$(path_for_cmd "$1")"
     cached="$configdir/$p"
     recent "$cached" || {
-        mkdir -p $(dirname "$cached")
+        mkdir -p "$(dirname "$cached")"
         curl -sf -o "$cached" "$base_url/$p"
     }
     # if the curl failed for some reason, keep cat from whinging
     cat "$cached" 2>/dev/null
 }
 
-heading() {
-    printf "%s\n" "${sheader}${*#??}$reset"
-}
-
-list_item() {
-    echo "${sdescription}$*$reset"
-}
-
-list_pages() {
-    for platform in $(ls "$configdir" )
-    do
-        for page in $(ls 2>/dev/null "$configdir"/"$platform/")
-        do
-            bname "$page" .md
-        done
-    done | sort | uniq
-}
-
-# Extract the platform key from index.json, return preferred subpath to tldrpage
-path_for_cmd() {
-    override="$configdir/local/$1.md"
-    if [ -f "$override" ]; then
-        echo "local/$1.md"
-        return
-    fi
-
-    # results in, eg, "name":"netstat","platform":["linux","osx"]},
-    desc=$(tr '{' '\n' < $index | grep "\"name\":\"$1\"")
-    [ -z "$desc" ] && echo "-- not found --" && return
-
-    # use the platform specific version of the tldr first
-    if contains $desc "$platform"; then
-        echo "$platform/$1.md"
-    elif contains $desc "common"; then
-        echo "common/$1.md"
-    else
-        # take the first one so we can show something, but warn the user
-        p=$(echo "$desc" | cut -d '"' -f 8)
-        >&2 printf "${red}tldr page $1 not found in $platform or common, using page from platform $p instead$reset\n"
-        echo "$p/$1.md"
-    fi
-}
-
-quotation() {
-    echo "${squote}${*#??}$reset"
-}
-
 # If the file exists and is more recent than '$cache_days' old.
 recent() {
     exists="$(find "$1" -mtime "-${cache_days}" 2>/dev/null)"
     [[ -n "$exists" ]] && [[ -z "$force_update" ]]
-}
-
-# FIXME Take this out...unnecessary.
-# FIXME Rethink the for loop approach here...
-style_for() {
-    style=""
-    # Sanitize user input. Only lowercase and spaces are allowed.
-    for i in $(printf %s "$*" | tr -cd '[a-z] ')
-    do
-        # FIXME Can we avoid the eval call here?
-        eval t="\$$i"
-        style="${style}${t}"
-    done
-    printf %s "$style"
-}
-
-
-style_params() {
-    printf %s "$*" | sed "s/{{/${sparam}/g;s/}}/${eparam}/g"
-}
-
-text() {
-    echo "$*"
-}
-
-trim() {
-    var="$*"
-    spaces=${var##*[! ]}
-    var=${var%"$spaces"}
-    spaces=${var%%[! ]*}
-    var=${var#"$spaces"}
-    printf %s "$var"
 }
 
 update_index() {
@@ -172,7 +131,87 @@ update_index() {
     return 0
 }
 
+# Visual styles  {{{2
+# ------------------------------------------------------------------------------
 
+code() {
+    # """
+    # Code block.
+    #
+    # @note Updated 2020-04-27.
+    #
+    # Take everything between two backticks, capture it, and surround it with
+    # styling.
+    # """
+    _koopa_print "$*" \
+        | sed "s/\`\([^\`]*\)\`/  ${scode}\1${reset}/g"
+}
+
+# FIXME Switch to using _koopa_h1 or something instead?
+heading() {
+    printf '%s\n' "${sheader}${*#??}$reset"
+}
+
+list_item() {
+    _koopa_print "${sdescription}$*$reset"
+}
+
+quotation() {
+    _koopa_print "${squote}${*#??}$reset"
+}
+
+style_params() {
+    printf '%s' "$*" \
+        | sed "s/{{/${sparam}/g;s/}}/${eparam}/g"
+}
+
+text() {
+    _koopa_print "$*"
+}
+
+
+
+
+
+
+
+
+
+# FIXME NEED TO CLEAN THIS ONE UP.
+# Extract the platform key from index.json, return preferred subpath to tldrpage
+path_for_cmd() {
+    override="${configdir}/local/${1}.md"
+    if [[ -f "$override" ]]
+    then
+        echo "local/${1}.md"
+        return 0
+    fi
+
+    # results in, eg, "name":"netstat","platform":["linux","osx"]},
+    desc=$(tr '{' '\n' < $index | grep "\"name\":\"$1\"")
+    [ -z "$desc" ] && echo "-- not found --" && return
+
+    # use the platform specific version of the tldr first
+    if _koopa_grepl "$desc" "$platform"
+    then
+        echo "$platform/$1.md"
+    elif _koopa_grepl "$desc" "common"
+    then
+        echo "common/$1.md"
+    else
+        # take the first one so we can show something, but warn the user
+        p=$(echo "$desc" | cut -d '"' -f 8)
+        >&2 printf "${red}tldr page $1 not found in $platform or common, using page from platform $p instead$reset\n"
+        echo "$p/$1.md"
+    fi
+
+    return 0
+}
+
+# Runners  {{{1
+# ------------------------------------------------------------------------------
+
+# FIXME This parser isn't currently working.
 
 # An idiot-level recognition of tldr's markdown. Needs improvement, or
 # subcontracting out to a markdown -> ANSI formatting command
@@ -181,11 +220,12 @@ display_tldr() {
     page="$1"
     page=$(style_params "$page")
 
-    # read one line at a time, don't strip whitespace ('IFS='), and process
-    # last line even if it doesn't have a newline at the end
+    # Read one line at a time, don't strip whitespace ('IFS='), and process
+    # last line even if it doesn't have a newline at the end.
     printf %s "$page" | while IFS= read -r line || [ -n "$line" ]; do
         # omit empty lines after list items
-        trimmed=$(trim "$line")
+        # FIXME IMPROVE THE NAME / STANDARDIZE THIS FUNCTION
+        trimmed=$(_koopa_trim_ws "$line")
         [ -z "$trimmed" ] && [ "$last_token" = "list_item" ] && continue
 
         case "$line" in
@@ -213,16 +253,72 @@ display_tldr() {
     done
 }
 
+list_pages() {
+    # """
+    # List locally cached tldr pages.
+    # @note Updated 2020-04-27.
+    # """
+    _koopa_h1 "Listing known tldr pages."
+    local pages
+    pages=()
+    while IFS= read -r -d $'\0'
+    do
+        pages+=("$REPLY")
+    done < <( \
+        find "$configdir" \
+            -mindepth 1 \
+            -type f \
+            -iname "*.md" \
+            -print0 \
+        | sort -uz
+    )
+    _koopa_basename_sans_ext "${pages[@]}"
+    return 0
+}
 
 
-# Config  {{{1
+
+# Argument parsing  {{{1
 # ==============================================================================
+
+# FIXME Switch to other approach used in bash scripts.
+while [ $# -gt 0 ]
+do
+    case "$1" in
+        -l|--list)
+            list_pages
+            exit 0
+            ;;
+        -n)
+            TLDR_CACHE=no
+            ;;
+        -u|-c|--cache|--update)
+            cache_tldr
+            exit 0
+            ;;
+        *)
+            # There are pages with hypens in them, such as 'git-tag'.
+            # This converts 'tldr git tag' to the hyphenated version.
+            hyphenated=$(printf %s "$*" | tr ' ' '-')
+            page=${hyphenated:-''}
+            break
+            ;;
+    esac
+    shift
+done
+
+
+
+# Configuration  {{{1
+# ==============================================================================
+
+# Colors  {{{2
+# ------------------------------------------------------------------------------
 
 # Contents via http://mywiki.wooledge.org/BashFAQ/037.
 reset="$(    tput sgr0   || tput me      )"  # Reset cursor
 bold="$(     tput bold   || tput md      )"  # Start bold
 underline="$(tput smul   || tput us      )"  # Start underline
-
 
 default="$(  tput op                     )"
 back="$(     printf '\b' )"
@@ -258,80 +354,47 @@ else
     eitalic="$(  tput ritm   || tput ZH      )"         # End italic
 fi
 
-
-
-
 # FIXME JUST PASS THE VARIABLE IN DIRECTLY HERE.
 # Custom styling if set in environment variables.
-sheader="$(style_for "${TLDR_HEADER:-red}")"
-squote="$(style_for "${TLDR_QUOTE:-underline}")"
-sdescription="$(style_for "${TLDR_DESCRIPTION:-reset}")"
-scode="$(style_for "${TLDR_CODE:-bold}")"
-sparam="$(style_for "${TLDR_PARAM:-italic}")"
-eparam="$(style_for "${TLDR_EPARAM:-eitalic}")"
+sheader="$red"
+squote="$underline"
+sdescription="$reset"
+scode="$bold"
+sparam="$italic"
+eparam="$eitalic"
 
+# Local configuration.
+configdir="${XDG_CONFIG_HOME}/tldr"
+index="${configdir}/index.json"
 
-
-
-# FIXME USE XDG CONFIG HERE.
-configdir=~/.tldr
-[ -d ~/.config ] && configdir=~/.config/tldr
-
-platform=$(get_platform)
+# tldr URLs.
 base_url="https://raw.githubusercontent.com/tldr-pages/tldr/master/pages"
 index_url="https://raw.githubusercontent.com/tldr-pages/tldr-pages.github.io/master/assets/index.json"
-index="$configdir/index.json"
+
+platform="$(get_platform)"
+
+
+
+# Cache / index  {{{1
+# ==============================================================================
+
+# Note that these are currently hard-coded.
 cache_days=14
 force_update=''
 
-#check if config folder exists, otherwise create it
-if [ ! -d "$configdir" ]; then
+# Check if config folder exists, otherwise create it.
+if [[ ! -d "$configdir" ]]
+then
     mkdir -p "$configdir"
     cache_tldr
 fi
 
-[ ! -f $index ] && update_index
+[[ ! -f "$index" ]] && update_index
 auto_update_index
 
 
 
-# Argument parsing  {{{1
-# ==============================================================================
-
-# FIXME Switch to other approach used in bash scripts.
-while [ $# -gt 0 ]
-do
-    case "$1" in
-        -l|--list)
-            >&2 printf "Known tldr pages: \n"
-            list_pages
-            exit 0
-            ;;
-        -n)
-            TLDR_CACHE=no
-            ;;
-        -p|--platform)
-            shift
-            platform=$1
-            ;;
-        -u|-c|--cache|--update)
-            cache_tldr
-            exit 0
-            ;;
-        *)
-            # There are pages with hypens in them, such as 'git-tag'.
-            # This converts 'tldr git tag' to the hyphenated version.
-            hyphenated=$(printf %s "$*" | tr ' ' '-')
-            page=${hyphenated:-''}
-            break
-            ;;
-    esac
-    shift
-done
-
-
-
-# Display tldr  {{{1
+# Display tldr page  {{{1
 # ==============================================================================
 
 # If the environment variable 'TLDR_CACHE=no', then fetch the page directly from
