Update tx2gene-from-ensembl-fasta

diff --git a/bin/tx2gene-from-ensembl-fasta b/bin/tx2gene-from-ensembl-fasta
--- a/bin/tx2gene-from-ensembl-fasta
+++ b/bin/tx2gene-from-ensembl-fasta
@@ -45,7 +45,7 @@ _koopa_help "$@"
 # Arguments                                                                 {{{1
 # ==============================================================================
 
-fasta="$1"
+fasta_file="$1"
 
 
 
@@ -54,14 +54,14 @@ fasta="$1"
 
 # Check for expected input.
 pattern=".cdna.all.fa.gz"
-if ! echo "$fasta" | grep -q "$pattern"
+if ! echo "$fasta_file" | grep -q "$pattern"
 then
-    >&2 printf "Error: Not Ensembl transcriptome FASTA: '%s'.\n" "$fasta"
+    >&2 printf "Error: Not Ensembl transcriptome FASTA: '%s'.\n" "$fasta_file"
     exit 1
 fi
 
-# Use of 7 here will include gene symbol.
-zcat "$fasta" | \
+# We're creating an invisible tmp file in current working directory here.
+zcat "$fasta_file" | \
     grep '>' | \
     cut -d ' ' -f1,4 > \
     .t2g
