Improve activation script

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -40,6 +40,113 @@
 
 
 
+# Flags                                                                     {{{1
+# ==============================================================================
+
+for i in "$@"
+do
+    case "$i" in
+        -h|--help)
+            help=1
+            ;;
+        --debug)
+            debug=1
+            ;;
+        --minimal)
+            minimal=1
+            export KOOPA_MINIMAL=1
+            ;;
+        --no-aspera)
+            aspera=0
+            ;;
+        --no-bcbio)
+            bcbio=0
+            ;;
+        --no-conda)
+            conda=0
+            ;;
+        --no-ensembl-perl-api)
+            ensembl_perl_api=0
+            ;;
+        --no-homebrew)
+            homebrew=0
+            ;;
+        --no-perlbrew)
+            perlbrew=0
+            ;;
+        --no-prompt)
+            prompt=0
+            ;;
+        --no-rbenv)
+            rbenv=0
+            ;;
+        --no-ssh-key)
+            ssh_key=0
+            ;;
+        --no-virtualenv)
+            virtualenv=0
+            ;;
+        --*|-*) # Unsupported flags.
+            >&2 printf "Error: Invalid flag %s\n" "$1"
+            exit 1
+            ;;
+    esac
+done
+
+
+
+# Help mode                                                                 {{{1
+# ==============================================================================
+
+if [ "${help:-0}" -eq 1 ]
+then
+    cat << EOF
+Activate koopa.
+
+Flags:
+
+    -h, --help
+        Help mode.
+
+    --debug, debug=1
+        Enable verbose debugging mode.
+    --minimal, minimal=1
+        Minimal mode. Simply export koopa programs into PATH.
+
+    --no-prompt, prompt=0
+        Skip prompt string customization. This disables PS1 export for bash,
+        and skips activation of pure prompt for zsh.
+
+    --no-aspera, aspera=0
+        Skip configuration of Aspera Connect.
+    --no-bcbio, bcbio=0
+        Skip configuration of bcbio-nextgen.
+    --no-conda, conda=0
+        Skip configuration of conda.
+    --no-ensembl-perl-api, ensembl_perl_api=0
+        Skip configuration of Ensembl Perl API.
+    --no-perlbrew, perlbrew=0
+        Skip configuration of Perl via perlbrew.
+    --no-rbenv, rbenv=0
+        Skip configuration of Ruby via rbenv.
+    --no-virtualenv, virtualenv=0
+        Skip configuration of Python virtual environment.
+
+Linux only:
+
+    --no-ssh-key, ssh_key=0
+        Skip loading of id_rsa default SSH key.
+
+macOS only:
+
+    --no-homebrew, homebrew=0
+        Skip configuration of Homebrew.
+EOF
+    exit 0
+fi
+
+
+
 # Set global options for debugging                                          {{{1
 # ==============================================================================
 
@@ -128,107 +235,6 @@ unset -v script_path
 
 # Get location of activation scripts.
 activate_dir="${KOOPA_DIR}/system/activate"
-
-
-
-# Flags                                                                     {{{1
-# ==============================================================================
-
-for i in "$@"
-do
-    case "$i" in
-        -h|--help)
-            help=1
-            ;;
-        --minimal)
-            minimal=1
-            export KOOPA_MINIMAL=1
-            ;;
-        --no-aspera)
-            aspera=0
-            ;;
-        --no-bcbio)
-            bcbio=0
-            ;;
-        --no-conda)
-            conda=0
-            ;;
-        --no-ensembl-perl-api)
-            ensembl_perl_api=0
-            ;;
-        --no-homebrew)
-            homebrew=0
-            ;;
-        --no-perlbrew)
-            perlbrew=0
-            ;;
-        --no-prompt)
-            prompt=0
-            ;;
-        --no-rbenv)
-            rbenv=0
-            ;;
-        --no-ssh-key)
-            ssh_key=0
-            ;;
-        --no-virtualenv)
-            virtualenv=0
-            ;;
-        --*|-*) # Unsupported flags.
-            >&2 printf "Error: Invalid flag %s\n" "$1"
-            exit 1
-            ;;
-    esac
-done
-
-
-
-# Help mode                                                                 {{{1
-# ==============================================================================
-
-if [ "${help:-0}" -eq 1 ]
-then
-    cat << EOF
-Activate koopa.
-
-Flags:
-
-    -h, --help         Help mode.
-
-    --minimal, minimal=1
-        Minimal mode. Simply export koopa programs into PATH.
-
-    --no-prompt, prompt=0
-        Skip prompt string customization. This disables PS1 export for bash,
-        and skips activation of pure prompt for zsh.
-
-    --no-aspera, aspera=0
-        Skip configuration of Aspera Connect.
-    --no-bcbio, bcbio=0
-        Skip configuration of bcbio-nextgen.
-    --no-conda, conda=0
-        Skip configuration of conda.
-    --no-ensembl-perl-api, ensembl_perl_api=0
-        Skip configuration of Ensembl Perl API.
-    --no-perlbrew, perlbrew=0
-        Skip configuration of Perl via perlbrew.
-    --no-rbenv, rbenv=0
-        Skip configuration of Ruby via rbenv.
-    --no-virtualenv, virtualenv=0
-        Skip configuration of Python virtual environment.
-
-    Linux only:
-
-    --no-ssh-key, ssh_key=0
-        Skip loading of id_rsa default SSH key.
-
-    macOS only:
-
-    --no-homebrew, homebrew=0
-        Skip configuration of Homebrew.
-EOF
-    exit 0
-fi
 
 
 
@@ -333,6 +339,7 @@ unset -v \
     aspera \
     bcbio \
     conda \
+    debug \
     help \
     homebrew \
     minimal \
