Improve quote consistency

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -215,8 +215,8 @@ _koopa_activate_export_prefix() { # {{{1
             # POSIX doesn't support file path resolution of sourced dot scripts.
             if [ ! -d "${KOOPA_PREFIX:?}" ] && _koopa_is_interactive
             then
-                printf "ERROR: Failed to locate koopa activation script.\n" >&2
-                printf "Required 'KOOPA_PREFIX' variable is unset.\n" >&2
+                printf 'ERROR: Failed to locate koopa activation script.\n' >&2
+                printf 'Required KOOPA_PREFIX variable is unset.\n' >&2
                 return 1
             fi
             KOOPA_ACTIVATE_SCRIPT="${KOOPA_PREFIX}/activate"
diff --git a/install b/install
--- a/install
+++ b/install
@@ -129,7 +129,7 @@ install() { # {{{1
                 break
                 ;;
             --*|-*)
-                printf 'ERROR: Invalid arg: "%s".\n' "$1" >&2
+                printf "ERROR: Invalid arg: '%s'.\n" "$1" >&2
                 return 1
                 ;;
         esac
@@ -141,7 +141,7 @@ install() { # {{{1
     # Before we proceed, ensure that koopa isn't already installed.
     if [[ -n "${KOOPA_PREFIX:-}" ]]
     then
-        printf 'ERROR: koopa is installed: "%s".\n' "$KOOPA_PREFIX" >&2
+        printf "ERROR: koopa is installed: '%s'.\n" "$KOOPA_PREFIX" >&2
         return 1
     fi
     script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
