Improve install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -30,34 +30,120 @@ optional arguments:
 
 note:
     Bash script.
-    Updated 2020-01-21.
+    Updated 2020-02-05.
 EOF
 }
 
-_koopa_group() {
+# shell/posix/functions/system.sh
+_koopa_group() {                                                          # {{{1
+    # """
+    # Return the approach group to use with koopa installation.
+    # Updated 2019-10-22.
+    #
+    # Returns current user for local install.
+    # Dynamically returns the admin group for shared install.
+    #
+    # Admin group priority: admin (macOS), sudo (Debian), wheel (Fedora).
+    # """
     local group
-    if groups | grep -Eq "\b(admin)\b"
+    if _koopa_is_shared_install && _koopa_has_sudo
     then
-        group="admin"
-    elif groups | grep -Eq "\b(sudo)\b"
-    then
-        group="sudo"
-    elif groups | grep -Eq "\b(wheel)\b"
-    then
-        group="wheel"
+        if groups | grep -Eq "\b(admin)\b"
+        then
+            group="admin"
+        elif groups | grep -Eq "\b(sudo)\b"
+        then
+            group="sudo"
+        elif groups | grep -Eq "\b(wheel)\b"
+        then
+            group="wheel"
+        else
+            group="$(whoami)"
+        fi
     else
         group="$(whoami)"
     fi
     echo "$group"
 }
 
-_koopa_has_sudo() {
-    [[ "$(id -u)" -eq 0 ]] && return 0
+# shell/posix/functions/assert.sh
+_koopa_has_passwordless_sudo() {                                          # {{{1
+    # """
+    # Check if sudo is active or doesn't require a password.
+    # Updated 2020-02-05.
+    #
+    # See also:
+    # https://askubuntu.com/questions/357220
+    # """
+    _koopa_is_installed sudo || return 1
+    sudo -n true 2>/dev/null && return 0
+    return 1
+}
+
+# shell/posix/functions/assert.sh
+_koopa_has_sudo() {                                                       # {{{1
+    # """
+    # Check that current user has administrator (sudo) permission.
+    # Updated 2020-02-05.
+    #
+    # This check is hanging on an CPI AWS Ubuntu EC2 instance, I think due to
+    # 'groups' taking a long time to return for domain users.
+    #
+    # Avoid prompting with '-n, --non-interactive', but note that this isn't
+    # supported on all systems.
+    #
+    # Note that use of 'sudo -v' does not work consistently across platforms.
+    #
+    # Alternate approach:
+    # > sudo -l
+    #
+    # List all users with sudo access:
+    # > getent group sudo
+    #
+    # - macOS: admin
+    # - Debian: sudo
+    # - Fedora: wheel
+    #
+    # See also:
+    # - https://serverfault.com/questions/364334
+    # - https://linuxhandbook.com/check-if-user-has-sudo-rights/
+    # """
+    # Always return true for root user.
+    [ "$(id -u)" -eq 0 ] && return 0
+    # Return false if 'sudo' program is not installed.
+    _koopa_is_installed sudo || return 1
+    # Early return true if user has passwordless sudo enabled.
+    _koopa_has_passwordless_sudo && return 0
+    # This step is slow for Active Directory domain user accounts on Ubuntu.
+    _koopa_assert_is_installed grep groups
     groups | grep -Eq "\b(admin|root|sudo|wheel)\b"
 }
 
-_koopa_is_linux() {
-    [[ "$(uname -s)" == "Linux" ]]
+# shell/posix/functions/assert.sh
+_koopa_is_linux() {                                                       # {{{1
+    # """
+    # Is the current operating system Linux?
+    # Updated 2020-02-05.
+    # """
+    [ "$(uname -s)" = "Linux" ]
+}
+
+# shell/posix/functions/assert.sh
+_koopa_is_local_install() {                                               # {{{1
+    # """
+    # Is koopa installed only for the current user?
+    # Updated 2019-06-25.
+    # """
+    echo "$KOOPA_PREFIX" | grep -Eq "^${HOME}"
+}
+
+# shell/posix/functions/assert.sh
+_koopa_is_shared_install() {                                              # {{{1
+    # """
+    # Is koopa installed for all users (shared)?
+    # Updated 2019-06-25.
+    # """
+    ! _koopa_is_local_install
 }
 
 piped=0
@@ -77,6 +163,7 @@ fi
 
 dotfiles=
 mike=0
+passwordless=0
 prompt=1
 shared=0
 test=0
@@ -184,6 +271,7 @@ then
         sudo chgrp "$group" "$prefix"
         sudo chmod g+ws "$prefix"
     fi
+
     echo "Downloading koopa."
     source_repo="https://github.com/acidgenomics/koopa.git"
     git clone --recursive "$source_repo" "$prefix"
@@ -211,6 +299,30 @@ set -u
 
 if [[ "$shared" -eq 1 ]]
 then
+    # Prompt if the user wants to enable passwordless sudo.
+    if [[ "$prompt" -eq 1 ]]
+    then
+        read -r -n 1 -p "Enable passwordless sudo (y/n)? " choice
+        case "$choice" in
+            y|Y)
+                passwordless=1
+                ;;
+            n|N)
+                passwordless=0
+                ;;
+            *)
+                >&2 echo "Error: Invalid input."
+                exit 1
+                ;;
+        esac
+        echo ""
+    fi
+
+    if [[ "$passwordless" -eq 1 ]]
+    then
+        _koopa_enable_passwordless_sudo
+    fi
+
     _koopa_update_profile
 fi
 
