Improve dotfiles install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,8 +2,6 @@
 # shellcheck disable=SC1090,SC1091,SC2162
 set -Eeu -o pipefail
 
-# FIXME THIS ISNT CREATING DOTFILES LINK IN CONFIG CORRECTLY.
-
 # """
 # koopa shell
 # https://koopa.acidgenomics.com/
@@ -60,7 +58,7 @@ END
 install() { # {{{1
     # """
     # Install koopa.
-    # @note Updated 2020-07-02.
+    # @note Updated 2020-07-07.
     # """
     local dotfiles interactive koopa_prefix passwordless profile shared test
     while (("$#"))
@@ -131,8 +129,8 @@ install() { # {{{1
                 break
                 ;;
             --*|-*)
-                printf "ERROR: Invalid arg: '%s'\n" "$1" >&2
-                exit 1
+                printf 'ERROR: Invalid arg: "%s"\n' "$1" >&2
+                return 1
                 ;;
         esac
     done
@@ -143,8 +141,8 @@ install() { # {{{1
     # Before we proceed, ensure that koopa isn't already installed.
     if [[ -n "${KOOPA_PREFIX:-}" ]]
     then
-        printf "ERROR: koopa is installed: '%s'.\n" "$KOOPA_PREFIX" >&2
-        exit 1
+        printf 'ERROR: koopa is installed: "%s".\n' "$KOOPA_PREFIX" >&2
+        return 1
     fi
     script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)"
     # Don't check for Bash version here, which will otherwise fail on macOS
@@ -153,8 +151,8 @@ install() { # {{{1
     # Check that temporary activation was successful.
     if [[ -z "${KOOPA_PREFIX:-}" ]]
     then
-        printf "ERROR: Installer failed to set 'KOOPA_PREFIX'.\n" >&2
-        exit 1
+        printf 'ERROR: Installer failed to set "KOOPA_PREFIX".\n' >&2
+        return 1
     fi
     # Ensure existing user configuration gets removed.
     rm -fr "$(koopa::config_prefix)"
@@ -185,12 +183,12 @@ install() { # {{{1
     then
         if [[ "$shared" -eq 1 ]] && [[ "$interactive" -eq 1 ]]
         then
-            shared="$(koopa::read_yn "Install for all users" "$shared")"
+            shared="$(koopa::read_yn 'Install for all users' "$shared")"
         fi
         # Set the default install prefix.
         if [[ "$shared" -eq 1 ]]
         then
-            prefix="/usr/local"
+            prefix='/usr/local'
         else
             XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME:?}/.local/share}"
             prefix="${XDG_DATA_HOME}"
@@ -200,7 +198,7 @@ install() { # {{{1
     # Prompt the user where they want to install.
     if [[ "$interactive" -eq 1 ]]
     then
-        koopa_prefix="$(koopa::read "Install prefix" "$koopa_prefix")"
+        koopa_prefix="$(koopa::read 'Install prefix' "$koopa_prefix")"
     fi
     # Catch if the user is attempting to install into a shared space.
     if [[ "$shared" -eq 0 ]] && \
@@ -213,12 +211,12 @@ install() { # {{{1
     # ==========================================================================
 
     # Alternatively, can consider using rsync here instead of cp.
-    koopa::h1 "Installing koopa at '${koopa_prefix}'."
+    koopa::h1 "Installing koopa at \"${koopa_prefix}\"."
     koopa::assert_is_non_existing "$koopa_prefix"
     if [[ "$shared" -eq 1 ]]
     then
-        koopa::info "Shared installation detected."
-        koopa::note "sudo permissions are required."
+        koopa::info 'Shared installation detected.'
+        koopa::note 'sudo permissions are required.'
         koopa::assert_has_sudo
         sudo mkdir -p "$koopa_prefix"
         sudo rm -fr "$koopa_prefix"
@@ -236,7 +234,7 @@ install() { # {{{1
     # Activate {{{1
     # ==========================================================================
 
-    koopa::h2 "Activating koopa."
+    koopa::h2 'Activating koopa.'
     set +u
     force=1 test="$test" source "${koopa_prefix}/activate"
     set -u
@@ -244,23 +242,23 @@ install() { # {{{1
     if [[ "${koopa_prefix:?}" != "${KOOPA_PREFIX:?}" ]]
     then
         >&2 cat << END
-ERROR: Installer failed to set 'KOOPA_PREFIX' correctly.
-Expected: '$koopa_prefix'
-Actual: '$KOOPA_PREFIX'
-PWD: '$PWD'
-BASH_SOURCE: '${BASH_SOURCE[0]}'
+ERROR: Installer failed to set KOOPA_PREFIX correctly.
+Expected: $koopa_prefix
+Actual: $KOOPA_PREFIX
+PWD: $PWD
+BASH_SOURCE: ${BASH_SOURCE[0]}
 END
-        exit 1
+        return 1
     fi
     # Check that activation puts koopa into PATH, as expected.
     if ! koopa::is_installed koopa
     then
         >&2 cat << END
-ERROR: Installer failed to set 'PATH' correctly.
-KOOPA_PREFIX: '$KOOPA_PREFIX'
-PATH: '$PATH'
+ERROR: Installer failed to set PATH correctly.
+KOOPA_PREFIX: $KOOPA_PREFIX
+PATH: $PATH
 END
-        exit 1
+        return 1
     fi
 
     # Passwordless sudo {{{1
@@ -272,7 +270,7 @@ END
         [[ "$shared" -eq 1 ]]
     then
         passwordless="$( \
-            koopa::read_yn "Enable passwordless sudo" "$passwordless" \
+            koopa::read_yn 'Enable passwordless sudo' "$passwordless" \
         )"
     fi
     [[ "$passwordless" -eq 1 ]] && koopa::enable_passwordless_sudo
@@ -287,16 +285,12 @@ END
         file="$(koopa::find_user_profile)"
         if [[ -e "$file" ]]
         then
-            koopa::note "User profile exists: '${file}'."
-            koopa::note "This will be overwritten if dot files are linked."
+            koopa::note "User profile exists: \"${file}\"."
+            koopa::note 'This will be overwritten if dot files are linked.'
         fi
-        dotfiles="$(koopa::read_yn "Install and link dot files" "$dotfiles")"
+        dotfiles="$(koopa::read_yn 'Install and link dot files' "$dotfiles")"
     fi
-    if [[ "$dotfiles" -eq 1 ]]
-    then
-        koopa::git_clone_dotfiles
-        koopa::install_dotfiles
-    fi
+    [[ "$dotfiles" -eq 1 ]] && koopa::install_dotfiles
 
     # User profile {{{1
     # ==========================================================================
@@ -306,8 +300,8 @@ END
     then
         if [[ "$interactive" -eq 1 ]]
         then
-            koopa::note "Koopa activation code needs to be added to '${file}'."
-            profile="$(koopa::read_yn "Modify '${file}'" "$profile")"
+            koopa::note "Koopa activation needs to be added to \"${file}\"."
+            profile="$(koopa::read_yn "Modify \"${file}\"" "$profile")"
         fi
         [[ "$profile" -eq 1 ]] && koopa::add_to_user_profile
     fi
@@ -319,11 +313,11 @@ END
     then
         koopa::remove_broken_symlinks "$koopa_prefix"
     else
-        koopa::note "Bash is very old and must be upgraded."
+        koopa::note 'Bash is very old and must be upgraded.'
     fi
     koopa::update_etc_profile_d
     koopa::fix_zsh_permissions
-    koopa::install_success "koopa"
+    koopa::install_success 'koopa'
     koopa::restart
     return 0
 }
