Improve RStudio Server install

diff --git a/os/fedora/sbin/install-rstudio-server b/os/fedora/sbin/install-rstudio-server
--- a/os/fedora/sbin/install-rstudio-server
+++ b/os/fedora/sbin/install-rstudio-server
@@ -9,15 +9,25 @@ source "$(koopa header fedora)"
 # See also:
 # - https://www.rstudio.com/products/rstudio/download-server/
 
+_koopa_assert_has_sudo
+
 name="rstudio-server"
 tmp_dir="$(koopa tmp-dir)/${name}"
 version="$(koopa variable "$name")"
 
 printf "Installing %s %s.\n" "$name" "$version"
 
-if _koopa_has_sudo
+sudo rm -rf /etc/rstudio
+
+# R 3.6.0 fix for missing libRblas.so file.
+if [[ ! -f "/usr/lib64/R/lib/libRblas.so" ]]
 then
-    sudo rm -rf /etc/rstudio
+    if [[ -f "/usr/local/lib64/R/lib/libRblas.so" ]]
+    then
+        sudo cp /usr/local/lib64/R/lib/libRblas.so /usr/lib64/R/lib/.
+    else
+        >&2 printf "Error: Missing '%s'.\n" "/usr/lib64/R/lib/libRblas.so"
+    fi
 fi
 
 file="rstudio-server-rhel-${version}-x86_64.rpm"
@@ -34,4 +44,8 @@ url="https://download2.rstudio.org/server/centos6/x86_64/${file}"
 
 command -v "$name"
 "$name" version
-"$name" status
+
+sudo "$name" stop
+sudo "$name" verify-installation
+sudo "$name" start
+sudo "$name" status
