Update interactive

diff --git a/bin/hpc/interactive b/bin/hpc/interactive
--- a/bin/hpc/interactive
+++ b/bin/hpc/interactive
@@ -66,11 +66,11 @@ export HPC_INTERACTIVE_JOB=1
 
 if [[ $HPC_SCHEDULER == "Slurm" ]]; then
     # X11 requires `~/.ssh/config` on local machine.
-    if [[ -n "$HPC_X11_FORWARDING" ]]; then
-        srun --cpus-per-task="$cores" --mem="${mem}G" --partition="$partition" --pty --time="$time" --x11="first" /bin/bash
-    else
-        srun --cpus-per-task="$cores" --mem="${mem}G" --partition="$partition" --pty --time="$time" /bin/bash
+    if [[ -z "$HPC_X11_FORWARDING" ]]; then
+        echo "X11 forwarding is required but not enabled"
+        exit 1
     fi
+    srun --cpus-per-task="$cores" --mem="${mem}G" --partition="$partition" --pty --time="$time" --x11="first" /bin/bash
 elif [[ $HPC_SCHEDULER == "LSF" ]]; then
     mem_mb="$(( $mem * 1024 ))"
     bsub -Is -n "$cores" -q "$partition" -R rhelp[mem="$mem_mb"] -W "$time" bash
