Improve updater

diff --git a/sbin/update-tex b/sbin/update-tex
--- a/sbin/update-tex
+++ b/sbin/update-tex
@@ -5,6 +5,8 @@ KOOPA_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." \
 # shellcheck source=/dev/null
 source "${KOOPA_HOME}/shell/bash/include/header.sh"
 
+_koopa_assert_has_sudo
+
 
 
 # Usage                                                                     {{{1
@@ -24,7 +26,7 @@ see also:
 note:
     Bash script.
     Requires that texlive is already installed.
-    Updated 2019-09-24.
+    Updated 2019-10-20.
 EOF
 }
 
@@ -35,6 +37,14 @@ _koopa_help "$@"
 # Script                                                                    {{{1
 # ==============================================================================
 
-tlmgr update --self
-tlmgr update --list
-tlmgr update --all
+if ! _koopa_is_installed tlmgr
+then
+    >&2 printf "Error: tlmgr is not installed.\n"
+    exit 0
+fi
+
+echo "Updating Tex Live."
+
+sudo tlmgr update --self
+sudo tlmgr update --list
+sudo tlmgr update --all
