Migrate cellar code

diff --git a/os/linux/bin/install-cellar-python b/os/linux/bin/install-cellar-python
--- a/os/linux/bin/install-cellar-python
+++ b/os/linux/bin/install-cellar-python
@@ -5,4 +5,66 @@ script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
 # shellcheck source=/dev/null
 source "${script_dir}/../include/header.sh"
 
-_koopa_cellar_script python
+# The '--enable-optimizations' flag can boost Python performance by ~10% but
+# currently runs into build issues with old compilation chains (e.g. GCC 4),
+# which are common on RHEL and other conservative cluster/VM configurations.
+# Therefore, we are disabling this flag by default.
+#
+# Recently, I'm seeing a new 'generate-posix-vars' error pop up with 3.8.0
+# installs on RHEL 7 machines.
+#
+# See also:
+# - https://bugs.python.org/issue33374
+# - https://github.com/pyenv/pyenv/issues/1388
+
+# Install libffi if you hit cryptic '_ctypes' module errors.
+# https://stackoverflow.com/questions/27022373
+
+name="python"
+version="$(_koopa_variable "$name")"
+prefix="$(_koopa_cellar_prefix)/${name}/${version}"
+tmp_dir="$(_koopa_tmp_dir)/${name}"
+build="$(_koopa_make_build_string)"
+jobs="$(_koopa_cpu_count)"
+exe_file="${prefix}/bin/python3"
+
+_koopa_message "Installing ${name} ${version}."
+
+if [[ -d "${HOME}/.virtualenvs" ]]
+then
+    _koopa_note "Removing existing virtual environments."
+    rm -frv "${HOME}/.virtualenvs"
+fi
+
+(
+    _koopa_cd_tmp_dir "$tmp_dir"
+    file="Python-${version}.tar.xz"
+    url="https://www.python.org/ftp/python/${version}/${file}"
+    _koopa_download "$url"
+    _koopa_extract "$file"
+    cd "Python-${version}" || exit 1
+    ./configure \
+        --build="$build" \
+        --prefix="$prefix" \
+        --enable-shared \
+        --without-ensurepip
+    make --jobs="$jobs"
+    # Multiprocessing tests can fail on very large multi-core VMs due to too
+    # many open files, so disable tests if necessary.
+    # > make test
+    make install
+    rm -fr "$tmp_dir"
+)
+
+_koopa_link_cellar "$name" "$version"
+
+_koopa_install_pip "$exe_file"
+_koopa_install_pipx "$exe_file"
+
+_koopa_link_cellar "$name" "$version"
+
+build_prefix="$(_koopa_make_prefix)"
+_koopa_message "Symlinking 'python3' to 'python' in '${build_prefix}'."
+ln -fnsv "${build_prefix}/bin/python3" "${build_prefix}/bin/python"
+
+_koopa_note "Reinstall cellar vim, which depends on Python."
