Update to pass lintr checks

diff --git a/host/azure/sbin/bcbio-admin-clean-anaconda-pkgs b/host/azure/sbin/bcbio-admin-clean-anaconda-pkgs
--- a/host/azure/sbin/bcbio-admin-clean-anaconda-pkgs
+++ b/host/azure/sbin/bcbio-admin-clean-anaconda-pkgs
@@ -15,7 +15,7 @@ pkgs_dir="${bcbio_dir}/${version}/install/anaconda/pkgs"
 
 if [[ ! -d "$pkgs_dir" ]]
 then
-    &>2 printf "Error: Packages directory does not exist.\n%s\n" "$pkgs_dir"
+    >&2 printf "Error: Packages directory does not exist: '%s'.\n" "$pkgs_dir"
     exit 1
 fi
 
diff --git a/host/azure/sbin/bcbio-admin-rsync-cpi b/host/azure/sbin/bcbio-admin-rsync-cpi
--- a/host/azure/sbin/bcbio-admin-rsync-cpi
+++ b/host/azure/sbin/bcbio-admin-rsync-cpi
@@ -5,7 +5,7 @@ set -Eeu -o pipefail
 source "$(koopa header azure)"
 
 # rsync bcbio installation.
-# Modified 2019-07-10.
+# Modified 2019-08-14.
 
 _koopa_assert_has_sudo
 
@@ -17,7 +17,7 @@ group="$(_koopa_build_prefix_group)"
 
 if [[ "$source_ip" == "$host_ip" ]]
 then
-    printf "Attempting to rsync from source machine.\n"
+    >&2 printf "Error: Attempting to rsync from source machine.\n"
     exit 1
 fi
 
diff --git a/host/azure/sbin/bcbio-admin-run-tests b/host/azure/sbin/bcbio-admin-run-tests
--- a/host/azure/sbin/bcbio-admin-run-tests
+++ b/host/azure/sbin/bcbio-admin-run-tests
@@ -21,20 +21,20 @@ tests_dir="${git_dir}/tests"
 
 if [[ ! -d "$bin_dir" ]]
 then
-    &>2 printf "Error: bcbio install does not exist.\n%s\n" "$bin_dir"
+    >&2 printf "Error: bcbio missing: '%s'.\n" "$bin_dir"
     exit 1
 fi
 
 if [[ ! -d "$tests_dir" ]]
 then
-    &>2 printf "Error: Failed to locate bcbio tests dir.\n%s\n" "$tests_dir"
+    >&2 printf "Error: bcbio tests missing: '%s'.\n" "$tests_dir"
     exit 1
 fi
 
 # Ensure temp SSD is configured correctly on Azure VM.
 if [[ ! -d "$tmp_dir" ]]
 then
-    &>2 printf "Error: Failed to detect tmp SSD.\n%s\n" "$tmp_dir"
+    >&2 printf "Error: Failed to detect tmpdir: '%s'.\n" "$tmp_dir"
     exit 1
 fi
 sudo chown "$USER" "$tmp_dir"
diff --git a/host/azure/sbin/symlink-docker b/host/azure/sbin/symlink-docker
--- a/host/azure/sbin/symlink-docker
+++ b/host/azure/sbin/symlink-docker
@@ -5,7 +5,7 @@ set -Eeu -o pipefail
 source "$(koopa header azure)"
 
 # Symlink docker installation.
-# Updated 2019-06-25.
+# Updated 2019-08-14.
 
 _koopa_assert_has_sudo
 
@@ -16,13 +16,13 @@ sudo service docker stop
 
 if [[ -d "$dest_dir" ]]
 then
-    >&2 printf "Error: Docker exists at %s.\n" "$dest_dir"
+    >&2 printf "Error: Docker exists: '%s'.\n" "$dest_dir"
     exit 1
 fi
 
 if [[ ! -d "$source_dir" ]]
 then
-    >&2 printf "Error: %s missing.\n" "$source_dir"
+    >&2 printf "Error: '%s' missing.\n" "$source_dir"
     >&2 printf "Check that Docker is installed.\n"
     exit 1
 fi
