Improve rsync config

diff --git a/host/azure/sbin/rsync-r-site-library b/host/azure/sbin/rsync-r-site-library
--- a/host/azure/sbin/rsync-r-site-library
+++ b/host/azure/sbin/rsync-r-site-library
@@ -66,11 +66,18 @@ fi
 sudo chgrp -Rh wheel "$r_dir"
 sudo chmod -R g+w "$r_dir"
 
-if [[ "$host_ip" != "$source_ip" ]]
+if [[ "$host_ip" == "$source_ip" ]]
 then
-    printf "Updating '%s' from '%s'.\n" "$r_dir" "$source_ip"
-    rsync -av --delete "${source_user}@${source_ip}:${r_dir}/" "${r_dir}/"
+    >&2 printf "Error: Attempting to sync from source machine.\n"
+    exit 1
 fi
+
+printf "Updating '%s' from '%s'.\n" "$r_dir" "$source_ip"
+rsync -av \
+    --delete \
+    --rsync-path="sudo rsync" \
+    "${source_user}@${source_ip}:${r_dir}/" \
+    "${r_dir}/"
 
 sudo chgrp -Rh wheel "$r_dir"
 sudo chmod -R g+w "$r_dir"
